### ISSUE TITLE
【后台】安全版块下的登录历史，条件搜索 所在地，需求是否存在？

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#101]
1、安全版块下的登录历史，条件搜索 中包括 所在地 输入搜索，但列表中并没有栏位显示 所在地，需确认搜索条件下拉框里 的 所在地是否有必要存在？
![46kwmay qq 8mp 0 pt_2g](https://user-images.githubusercontent.com/35476103/35204151-342f6e92-ff67-11e7-8bd1-86514be8e9db.jpg)

**Comment by patrickkh7788** [comment]
重复问题。

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/55

**Comment by tonyisid** [comment]
已经修正过滤条件

**Comment by ruoktest** [comment]
确认

**Comment by ruoktest** [comment]
已验证
