### ISSUE TITLE
【后台】版块工具下的聊天室 新建聊天室点击没有反应，需确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#102]
![xjdrahbm8 e 32d90iv0015](https://user-images.githubusercontent.com/35476103/35204652-9afd094c-ff6a-11e7-925a-daf31553a45e.png)

**Comment by tonyisid** [comment]
UI上没有新建按钮，已经移除

**Comment by ruoktest** [comment]
已确认
