### ISSUE TITLE
【后台】工具下 的红包列表 点击查看红包详情，内页为空，与列表内容不相符合

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#103]
![yo a5r 3v6b55or3 de u](https://user-images.githubusercontent.com/35476103/35204785-5cd2b332-ff6b-11e7-8ab4-c6308e0aae18.png)

**Comment by patrickkh7788** [comment]
前台需要添加： 
```json
{
"user_details": {
"username": "972428057",
"user_type": "直属会员",
"user_level": "默认",
"created_at": "2017-11-28 20:51:13",
"total_order_amount": "￥0.00",
"today_cash_in_amount": "￥0.00"
}
}
```

**Comment by tonyisid** [comment]
已经修复

**Comment by ruoktest** [comment]
请协助确认领取人明细下信息是否需要做相关字段添加，感谢
![image](https://user-images.githubusercontent.com/35476103/35253972-333118c6-0023-11e8-8d71-02ea0ca41bd7.png)

**Comment by bihuademon** [comment]
是的，需要这些字段的@patrickkh7788

**Comment by tonyisid** [comment]
这些字段的数据已经有了，还需要哪些字段？

**Comment by bihuademon** [comment]
那就把这些数据做进来就好，目前我看到还是没有@tonyisid

**Comment by patrickkh7788** [comment]
列表里我也添加了这几个字段（见文档）。

**Comment by tonyisid** [comment]
加上了
