### ISSUE TITLE
【后台】财务版块下的 人工取出页面 查询框显示的 会员账号 人工取出 需确认功能？

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#104]
1、财务版块下的 人工取出页面 查询框显示的 会员账号 人工取出 需确认功能？是否为按钮可点击
2、两者字体颜色不同，UI是否需要修改
![545 7 ehs6_z2xp i y xc](https://user-images.githubusercontent.com/35476103/35208029-141c6dc0-ff81-11e7-8b5e-c617d8cd0b9a.png)

**Comment by 205043957** [comment]
人工取出 不是一个按钮，只是一个显示信息,

**Comment by 205043957** [comment]
为了不混淆，已由和按钮一样的绿色改为黑色

**Comment by ruoktest** [comment]
已确认
