### ISSUE TITLE
【后台】财务版块下的金流记录，输入金额进行查询，显示出结果不准确

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#105]
![jinrmrwz mjdo6 nj9a xsa](https://user-images.githubusercontent.com/35476103/35208169-cf06a7d6-ff81-11e7-9d2a-be98ebb81f42.png)

**Comment by patrickkh7788** [comment]
重复
https://github.com/ruoklive/lottery_bug/issues/71

**Comment by tonyisid** [comment]
文案改成最小金额

**Comment by ruoktest** [comment]
已验证
