### ISSUE TITLE
【后台】财务版块下的存取款记录搜索条件中有IP、接收人、审核人，列表中并无此项

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#106]
![40_03to arho0yl_pc 2umo](https://user-images.githubusercontent.com/35476103/35208501-ce05bf28-ff83-11e7-9fd4-bc51056f8903.png)

**Comment by patrickkh7788** [comment]
去掉这几个条件。

**Comment by tonyisid** [comment]
已经去掉这几个条件选项

**Comment by ruoktest** [comment]
已验证
