### ISSUE TITLE
【后台API】彩票香港六合彩后台显示开盘中，前台却显示为开盘，无法购买，请确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#107]
![hqcxl k8wc867r0r3i6g 3](https://user-images.githubusercontent.com/35476103/35255588-b98b09c0-002a-11e8-91e1-c276da7af7ac.png)

**Comment by patrickkh7788** [comment]
pc前端需要参照mobile处理方式去修改开盘判断。

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/169

**Comment by patrickkh7788** [comment]
http://frontendPC前台显示的状态： https://api.ruok.co/cn/cgi/api/current_issue_no?item_code=xglhc
可以根据 time （剩余秒数）来处理。
对香港六合彩来说， 在开奖后的一段时间内，如果上一期没有开出来，下一期是不能购买的。也就是自动封盘了。

**Comment by chansent** [comment]
已添加封盘显示逻辑
