### ISSUE TITLE
【ios】【android】【注册】在app里进行注册 ，如果国家选择其它国家时，验证码随便输入都可以注册 成功

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#109]
1、输入用户名：aaaaaa
2、选择国家：Argentina
3、输入手机号：10000000000
4、输入发送的验证码：123（随便填写了一个数字）
5、密码：12345678a
6、点击注册

7、注册成功，应该弹出提示，请输入正确的验证码

**Comment by huangjianguohjg** [comment]
刚才经过沟通，现在后台直接为了你们注册方便，不需要改手机号改来该去，任何手机号都可以注册成功

**Comment by ruoktest** [comment]
验证通过，关闭
