### ISSUE TITLE
后台报表玩法输出需要校对一下

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#11]
1-后台报表玩法输出需要校对一下，
2-后台报表需要将下注内容也体现出来，    官方彩可显示几个字节，具体在详情内查看，但传统彩要能正常显示。

![a1](https://user-images.githubusercontent.com/35476103/34989755-4df6eb5e-faf6-11e7-9962-f402fc9e590a.jpeg)
![a2](https://user-images.githubusercontent.com/35476103/34989768-57e64f88-faf6-11e7-93d8-a8a0621d2e30.jpeg)

**Comment by tonyisid** [comment]
现在这个列表的字段有些多，再加入字段后，在1028的屏幕上会有问题。
UI看看怎么加上？

**Comment by bihuademon** [comment]
有效金额，投注金额的宽度再窄一点，标题"玩法"改在"玩法（投注内容）"，列表对应的格式如：第四球(2)，或放不下时就：定位胆…（4,5,6）
这些括号逗号都用英文的符号
@tonyisid

**Comment by ruoktest** [comment]
确认
