### ISSUE TITLE
【后台】公司入款申请-已确认，但在存取款纪录里面未显示纪录。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#110]
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35265477-c812eff8-0052-11e8-8a63-c6fcb36c1c9e.png">
红色框内为确认审核之前的截图，
在存取款纪录里面没有正常显示，单独查询 972431860  这个会员，也查不到他的纪录。

同时我又操作了一笔该会员的提款，同样也是没有显示，也查不到。

---------------------------
同时存在另一个问题：在存取款纪录页面，查看到该会员之前的纪录，点击该纪录，进入到会员明细页面，显示空白。

<img width="1279" alt="a7" src="https://user-images.githubusercontent.com/35476103/35266063-a5f88f34-0054-11e8-8530-a2070b678229.png">
<img width="1279" alt="a8" src="https://user-images.githubusercontent.com/35476103/35266064-a62cedb0-0054-11e8-950c-80de3d347bc0.png">

**Comment by patrickkh7788** [comment]
这个是UI过滤器默认选择了异常状态，应该修改为全部状态。

@205043957 nick 你看下 https://testadmin.ruok.co/admin.html#/userDetail/1044/orders 这个账户明细页面的过滤器是有问题的，一起修复一下。

**Comment by patrickkh7788** [comment]
从用户明细页的存取款记录，没有办法跳转到财务下面的存取款记录。

**Comment by 205043957** [comment]
财务过滤以及增加字段显示的，昨天我已经修复提交代码了

**Comment by ruoktest** [comment]
确认
