### ISSUE TITLE
【后台】存取款纪录页面新增-存款优惠-其它优惠，取款类型底色调整。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#111]
<img width="1279" alt="a9" src="https://user-images.githubusercontent.com/35476103/35266488-084f1698-0056-11e8-9258-b51904b7660d.png">

存取款报表界面新增    存款优惠--其它优惠    ，同时底部也需要增加其它优惠的统计，并且后面的总计工式需要做相应的调整。
    如若横向空间不足，可调节   序号   交易码   申请时间    状态   审核时间        这几个项目的空间调小。

计算公式--特别注意   我们的取款金额数值表现为负值
存取款收支：  存款金额  +  取款金额    
总收支：存款金额-存款优惠-其它优惠+取款金额    
-------------------
增加出款与入款的颜色差异，    出款(包含会员提款，以及人工取出）显示整行底色，具体色值可与UI确定。

<img width="1279" alt="a3" src="https://user-images.githubusercontent.com/35476103/35266524-1ee8dc5e-0056-11e8-9452-911c94d43a9a.png">

**Comment by ruoktest** [comment]
新增：将  存取款方式   一栏下的   提款    方案修改为   在线取款

**Comment by patrickkh7788** [comment]
API 存取款收支以及总收支计算公式已经调整。

**Comment by ruoktest** [comment]
确认
