### ISSUE TITLE
【阿阳-PC端】---会员中心，取款功能无法正常使用--优先处理！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#113]
<img width="1140" alt="a9" src="https://user-images.githubusercontent.com/35476103/35271857-f958c886-0065-11e8-87ad-086f3eb80659.png">
会员中心，取款功能无法正常使用--优先处理！

**Comment by chansent** [comment]
已经提了一版可供调试

**Comment by ruoktest** [comment]
1-29号阿阳复检：PC取款不正常。
<img width="1179" alt="a2" src="https://user-images.githubusercontent.com/35476103/35495341-11e7788e-04f3-11e8-8bb9-a97e0a72f972.png">
