### ISSUE TITLE
【后台】用户详情-交易数据里面的存取款功能

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#115]
<img width="1278" alt="a9" src="https://user-images.githubusercontent.com/35476103/35279359-7b8d6528-007f-11e8-8491-51a022881739.png">
个人里面的存取款界面保持与   存取款报表一致。

但无需保留多余的选择项目，  可在   清空筛选   那栏 靠右侧增加    今日  昨日  本周   上周   本月   上月  全部

去掉选择项目理由：这里已经是精准到个人用户的数据了，相对来讲数据很少，不需要在保留总表上面的筛选项目。

**Comment by bihuademon** [comment]
是的，包括个人里的存取款页面左边的tab去了，多余了。@tonyisid

**Comment by 205043957** [comment]
![image](https://user-images.githubusercontent.com/18372025/35469264-28724e98-0364-11e8-8d92-c2c8fef1479d.png)

**Comment by 205043957** [comment]
这个时间还是保留，这个时间筛选里面包含 今天，昨天等等时间选项，其它的页面显示和过滤我删除了
