### ISSUE TITLE
【pc】首页 > 会员列表 > 会员  变更内容显示问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#120]
![wx20180124-012012](https://user-images.githubusercontent.com/35476103/35310808-3da2b866-00ee-11e8-9089-be0434300328.png)

**Comment by patrickkh7788** [comment]
请提供更详细描述，需要变更哪些内容显示。
如果是包括UI的变动，需要同时加上Backend-UI的标签。

**Comment by patrickkh7788** [comment]
@WWcodeTW 
充值日志需要修改为。  操作内容：  充值50元， 原始内容（用户初始账户值），变成内容（操作后账户值）。
