### ISSUE TITLE
【后台】子账号设定部分功能没有相关权限（查看&操作），在[全部]版块下依旧显示所有功能项

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#128]
1、后台创建子账户：wl654  密码：666666
2、设置相关权限如下图，用子账号登录后台后，确认该账号没有权限的 子项依旧在[全部]下展示出来
![i lm tv sm 7ze r q2o wr](https://user-images.githubusercontent.com/35476103/35319729-09c11b7c-011c-11e8-8c75-b7660d7a80f0.png)
![ct0ekdsd9h6twizlybmxe_x](https://user-images.githubusercontent.com/35476103/35319732-0c77b376-011c-11e8-842a-5b2d5d609c4e.png)

**Comment by tonyisid** [comment]
这个是一个bug，需要在全部菜单里面过滤没有相关权限的菜单

**Comment by tonyisid** [comment]
已经修改了，请复查

**Comment by ruoktest** [comment]
已验证
