### ISSUE TITLE
【后台】点击后台退出按钮，会出现返回的页面为空白，而不是直接返回到登录界面（非必现）

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#131]
1、点击后台退出按钮，会出现返回的页面为空白，而不是直接返回到登录界面（非必现）
Chrome win7系统
![e gi 72 dl6hbg __2 8n6](https://user-images.githubusercontent.com/35476103/35320839-2b445e04-0120-11e8-95ed-91464584a3b8.png)
![yffkr7 9w u fbukl9](https://user-images.githubusercontent.com/35476103/35320841-2d37b742-0120-11e8-8996-5fd625d56627.png)

**Comment by HangZyc** [comment]
跟 issue 165 是同一个问题。https://github.com/ruoklive/lottery_bug/issues/165
目前已修复。
