### ISSUE TITLE
【后台】模块 （总）代理、会员、子账号这是设定页面，已经设置登录密码和银行卡之类的密码，但下次进入后依旧为空

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#132]
![3wq ptxcf90 0xrcdz 6f1](https://user-images.githubusercontent.com/35476103/35321111-205b238c-0121-11e8-8f1e-125cfb40a0b2.png)

**Comment by tonyisid** [comment]
这个应该不算Bug，后端不能把密码回传过来。用户要修改就填写新密码，不填就不改密码。

**Comment by ruoktest** [comment]
确认
