### ISSUE TITLE
【子账号】创建子账号且给予 [注单账号]的查看权限，不给操作权限，但登陆后依旧阔以点击操作栏的详情

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#134]
![1 b55 7 lkaey369 cb i](https://user-images.githubusercontent.com/35476103/35323515-bc29ea8a-0128-11e8-990c-1a1125c3f5f8.png)
![ea 4qhbet4im aut 2y1](https://user-images.githubusercontent.com/35476103/35323521-beaa8fd0-0128-11e8-92c3-69aabf037e68.png)

**Comment by tonyisid** [comment]
点详情是属于权限中的查看范畴

**Comment by ruoktest** [comment]
ok
