### ISSUE TITLE
【后台】子账号只有查看权限，无操作权限，但子账号登录后以下页面依旧可操作，请确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#136]
1、子账号：wl654    密码：666666       正常登录，后台设置只有查看权限，没有操作权限
版块：财务下的 存取款记录、人工存入、人工取出  依旧可操作，需确认
![r wuv1u allvq y m_4t a](https://user-images.githubusercontent.com/35476103/35325476-daa27652-012e-11e8-88cc-9f9cdceb007f.png)

**Comment by ruoktest** [comment]
1、后台设置子账号，不给操作权限，功能未实现---->子账号登录后，所有子功能都阔以操作，和给没给权限没啥区别
![ak4o d jss3 0nkzpc y5h](https://user-images.githubusercontent.com/35476103/35326048-70a9dc34-0130-11e8-9ccc-3f30d08ef7f5.png)

**Comment by tonyisid** [comment]
人工入款/出款的权限判断在点击“确定按钮”。
目前的权限是有查看界面就可以进入相关页面进行查看，但是不能进行编辑操作。

**Comment by ruoktest** [comment]
请问修改权限后，是否会有缓存，多久？因为发现这个权限的东西测了好几遍，都有不同的结果

**Comment by tonyisid** [comment]
权限是存在浏览器内存中。跟每次登陆的session一致。每次登陆，或者刷新页面都会更新权限
