### ISSUE TITLE
【后台】增加推广域名，并将域名设置为默推广域名，访问出现大量不正常!!!!

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#137]
<img width="1274" alt="a1" src="https://user-images.githubusercontent.com/35476103/35329219-a1aaa880-0131-11e8-91a7-56e2e1790914.png">

域名：ruok666.com

<img width="1266" alt="a2" src="https://user-images.githubusercontent.com/35476103/35329223-a27f77ae-0131-11e8-9435-bd90defae9e5.png">

**Comment by ascar5** [comment]
本地访问正常
