### ISSUE TITLE
【后台】【会员】新增会员填写完资料后，显示没有权限

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#138]
【后台】【会员】新增会员填写完资料后，显示没有权限
![2](https://user-images.githubusercontent.com/35476103/35329668-a9fa2b00-013b-11e8-9c92-f58ae82d4cc1.png)

**Comment by tonyisid** [comment]
已经加上权限密码的输入框

**Comment by ruoktest** [comment]
验证通过，关闭
