### ISSUE TITLE
【客户端】ios、Android 订单状态为 已撤销时，显示错误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#140]
1、注单号：20180125105022414353，已将其状态改为：已撤销
2、查看确认：a、PC端显示正确，状态为 已撤销（之前提过）
                        b、ios  全部订单下该订单在右下角的状态 为空
                        c、Android 全部订单下 右下角的状态为  未中奖
以上需确认修改
![dtcigkkg h v o ciu9in7](https://user-images.githubusercontent.com/35476103/35368543-bca77bd0-01be-11e8-8642-105edfabe0c8.png)
![1dd 1 c g eec3x fjdn](https://user-images.githubusercontent.com/35476103/35368555-c8fd9a9a-01be-11e8-9cd4-ff48cd12cc83.jpg)
![g cuh jt rz wtag 2yl7](https://user-images.githubusercontent.com/35476103/35368565-d5628872-01be-11e8-9b19-8ad96cf6894e.jpg)

**Comment by huangjianguohjg** [comment]
后台增加了 新的异常值，前台未加新的撤单之后的判断，现在已添加

**Comment by edem** [comment]
Android 也已追加判斷式, 目前等後台API修正後再試.
