### ISSUE TITLE
【后台】子账号设定功能[公司入款申请]有查看权限，但没有操作权限，提示文案错误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#146]
1、点击 公司入款进行查看，可确认相关资料
2、点击审核，提示文案 ：错误          无操作权限是否提示：没有权限 或其它
![ibp r1k qo2q si ga j8](https://user-images.githubusercontent.com/35476103/35374726-2462cda4-01df-11e8-81d6-c28b8232067b.png)

**Comment by ruoktest** [comment]
问题：如上用户wl654 密码：666666
3、点击线上入款申请时，没有操作权限下点击审核，弹出框无内容
![g6x alhqqj8 gfdpnoa](https://user-images.githubusercontent.com/35476103/35374867-b38f0d44-01df-11e8-9872-78477996426b.png)

**Comment by tonyisid** [comment]
修正了权限错误

**Comment by ruoktest** [comment]
确认
