### ISSUE TITLE
【后台】设定子账号无相关操作权限，点击功能：等待出款、及时出款信息，依然可操作

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#147]
子账号wl654，密码：666666
1、设定其无任何操作权限，但有查看权限，，点击功能：等待出款、及时出款信息，操作栏依旧阔以正常操作 审核、通过
![8 6kmv0rjuki 4 o ad 96](https://user-images.githubusercontent.com/35476103/35375642-bc3d3da0-01e2-11e8-8fc6-02c67b1af1a0.jpg)

**Comment by ruoktest** [comment]
问题2：点击功能：产品赔率设置   可正常修改
![bz6 2l cni 7hfdkvg py x](https://user-images.githubusercontent.com/35476103/35375853-80389092-01e3-11e8-913f-79836bbc7874.png)
问题3、点击功能群聊，无操作权限-----实际点击设置无反应，是否设置提示框：没有权限
![fn2j3 lr b x pi7c nniv0](https://user-images.githubusercontent.com/35476103/35376691-297d4bcc-01e7-11e8-87cf-52112eb6eb29.png)

**Comment by tonyisid** [comment]
1. 昨天已经修复了，请刷新页面复查一遍。
2、3我再确认一下

**Comment by tonyisid** [comment]
2,3 已经修复
