### ISSUE TITLE
【阿阳-后台】用户详情页面，标签无法正常使用。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#148]
<img width="1279" alt="a1" src="https://user-images.githubusercontent.com/35476103/35376548-31d84a32-01de-11e8-83a5-144439bb7230.png">

只有详情跟设定可点，其它均无法切换。

**Comment by tonyisid** [comment]
请再确认一下这个bug，我这里没有重现

**Comment by ruokco** [comment]
update step
backend-ui 2.5

**Comment by ruoktest** [comment]
2-7号复检没问题。
