### ISSUE TITLE
【阿阳-后台】财务-存取款纪录--查询功能不正常！！！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#151]
<img width="1150" alt="a1" src="https://user-images.githubusercontent.com/35476103/35377442-ce3098c8-01e1-11e8-8581-ac0545194720.png">
<img width="1277" alt="a2" src="https://user-images.githubusercontent.com/35476103/35377443-ce64bdd8-01e1-11e8-902f-b8ffa4116e01.png">

如图一所示，所选入款成功，  在纪录列表也可看得到，   
但过滤选择时，提示不正常。

**Comment by patrickkh7788** [comment]
已经修复！

**Comment by ruoktest** [comment]
2-2号复测   不正常···！！！
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35719128-75b47662-081a-11e8-9d0e-a7346d0fd510.png">
#221    不知与这个错误是否有关链，请自行判断检查。

**Comment by ruokco** [comment]
backend-end 2.8

**Comment by patrickkh7788** [comment]
@ruoktest 测试不能重现。

**Comment by ruoktest** [comment]
2-8号复测OK
