### ISSUE TITLE
【后台】子账户对功能：盘口/赔率没有操作权限，但依旧阔以修改，请确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#153]
1、子账号：wl654   密码：666666
2、子账户对功能：盘口/赔率没有操作权限，但依旧可以操作修改成功
![oxr sex _u zws5 1bxu](https://user-images.githubusercontent.com/35476103/35378389-96310bd6-01ed-11e8-8878-beab0623bfae.png)

**Comment by patrickkh7788** [comment]
后台权限限制错误已经修复。
@tonyisid 前台使用子账号登录，及时已经授予全部权限，仍然没有办法看到产品设置导航项目。

**Comment by ruoktest** [comment]
已确认
