### ISSUE TITLE
【后台】子账号设置相关权限，需确认以下功能的测试点如何确认？

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#154]
1、设定子账号wl654  密码666666  给定权限如下图
2、例 首页面的 【主钱包】给查看&操作权限，不给查看&操作权限      都是一样的效果
这是bug吗
![e8354q2rry8 4es0d_a i5](https://user-images.githubusercontent.com/35476103/35379490-3119c270-01f1-11e8-9571-e5102aca14a4.png)

**Comment by tonyisid** [comment]
首页的模块还没有绑定权限
UI是否能够给出需求？

**Comment by patrickkh7788** [comment]
后台加了检查，没有权限输出的0.

**Comment by ruokco** [comment]
2.5 backend-ui

**Comment by HangZyc** [comment]
@ruoktest 
依据下面的需求，首页权限功能已经加好。
---
移动设备应该只给 _login_master_super 的用户显示
存取款 以及投注额， 会员钱包余额 根据当前用户的权限view 来判断
没有存取记录的权限，就不能看存取款
没有注单报表权限，就不给看投注
