### ISSUE TITLE
【阿阳-后台】存取款纪录表格需要优化

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#155]
<img width="1276" alt="a3" src="https://user-images.githubusercontent.com/35476103/35380072-c8511ffa-01ea-11e8-8d90-c19137c45839.png">
如图所示， 订单编码， 申请时间/  审核时间，三个表格显示不完整

建议可将  存款优惠， 其它优惠表格缩小至  保留存到  99999.00   这样的宽度即可

**Comment by tonyisid** [comment]
宽度我更改过了
但是东西太多了，在1024宽度的屏幕下还是会看不到一些数据。
