### ISSUE TITLE
【后台】财务版块下的存取款记录，输入存款金额金勋查询 显示不对

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#156]
1、此处文案是否是  最小金额（实际显示的也是最小金额）
![nlc 4j yhvti 0u 0iov](https://user-images.githubusercontent.com/35476103/35380737-1a1a11a2-01f5-11e8-9022-043504e02dd7.png)

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/71

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已验证
