### ISSUE TITLE
【阿阳-后台】报表-交收汇总报表处金额新增点击标签

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#157]
<img width="1278" alt="a5" src="https://user-images.githubusercontent.com/35476103/35380718-ad8be6c6-01ec-11e8-82ef-a3fe307a24b0.png">

**Comment by patrickkh7788** [comment]
清单列表就是注单报表，根据时间以及parent_user_id选择。

**Comment by ruoktest** [comment]
不太一样的，你通过查询出来的是所有，而我这里点击进入是有针对性的显示，
且增加快捷金额点击方便运营商操作。

**Comment by patrickkh7788** [comment]
我是给UI提示， 通过这个API以及参数可以选择出需要的数据结果。

**Comment by tonyisid** [comment]
交收报表里面弹出注单报表？
请确认一下逻辑。是否跳转到注单报表页面？
如果放在tab里面，顶部的查询逻辑会有问题

**Comment by patrickkh7788** [comment]
我觉得跳转比较好。

**Comment by tonyisid** [comment]
目前应该也只能按照跳转做。
@luispuentesvega  you can add link to orderReport, add params in query.

**Comment by tonyisid** [comment]
跳转之后可以在注单报表打开相应的用户注单tab，但是传入彩种有些困难

**Comment by ruoktest** [comment]
<img width="1273" alt="a3" src="https://user-images.githubusercontent.com/35476103/35495419-6adfeaa2-04f3-11e8-899f-86041f48e60a.png">
1-29号阿阳复检，  这里金额点击后，快捷显示 这些金额的来源列表。

至于是要跳转还是 TAP如何实现则由老杨去决定。

**Comment by patrickkh7788** [comment]
The member total amount:
   https://admin.ruok.co/cn/api/user/orders/history?user_id=277&from=20180101&to=20180112
The member total  valid amount:
   https://admin.ruok.co/cn/api/user/orders/history?user_id=277&from=20180101&to=20180112&filters[is_valid]=1

the agent total amount:

   https://admin.ruok.co/cn/api/user/orders/history?parent_user_id=91&from=20180101&to=20180112

the agent valid amount:
   https://admin.ruok.co/cn/api/user/orders/history?parent_user_id=91&from=20180101&to=20180112&filters[is_valid]=1

to show the correct amount number, you has to bypass the date(from,to).

**Comment by luispuentesvega** [comment]
It was solved with the commit  (b882c6e483a589c5d9d520053ed98fcdc8ee6839) "fix bug157"

**Comment by ruoktest** [comment]
1-31号阿阳复测：目前金额可点，存在已下注未结算，汇总交收报表处 有效金额为  0.00   点击时，跳出的所有未结算注单。
<img width="1279" alt="a5" src="https://user-images.githubusercontent.com/35476103/35605336-d0d138e2-067a-11e8-8c7c-01a2fce68159.png">
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35605339-d447ebc4-067a-11e8-996f-8bffa95de7b8.png">

**Comment by tonyisid** [comment]
看到有API了。
那是不是还要在注单报表上面加一个是否有效的过滤条件？

**Comment by ruoktest** [comment]
2-2号复测，点击有效金额仍然会带出 已下注未结算的注单。

**Comment by ruokco** [comment]
backend-ui 2.5

**Comment by tonyisid** [comment]
已经加上filters[is_valid]=1条件，但是数据还是不对， @patrickkh7788 看下

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/202

**Comment by patrickkh7788** [comment]
已经修复统计问题，需要传如 by_update参数。

**Comment by ruoktest** [comment]
2-8号复测OK
