### ISSUE TITLE
【后台】安全下的登录历史 搜索条件输入 登录账号时，点击搜索无反应

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#158]
![ob i yglup i gd vqoi](https://user-images.githubusercontent.com/35476103/35382648-d67d7e2e-01fa-11e8-998b-fb91dff81048.png)

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/55

**Comment by ruoktest** [comment]
已确认
