### ISSUE TITLE
【后台】子账号 wl654 密码 666666 登录后台后，在登录历史中没有找到香港信息

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#159]
1、创建子账号 wl654  密码666666
2、01/24—01/25期间多次登录后台
3、用账号test 登录后台查看安全下的登录历史，列表显示信息无 wl654，请协助确认

**Comment by codeistalk** [comment]
@ruoktest , tested on back end. Its working Perfectly.
