### ISSUE TITLE
【阿阳-后台】报表  交收汇总报表一栏   平台输赢

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#160]
目前系统将用户下注，未结算的注单也归属于   平台赢钱 统计里面，

正确的是：未结算的注单只纪录到总投注额一栏，其它栏是不计算的！！包括尾部的会员总计，股东直属等

所有报表里面涉及到输赢一荐的，均不能包含未结算金额！！！！

**Comment by patrickkh7788** [comment]
现在已经修改为使用有效投注来计算 输赢总计等金额。

**Comment by ruoktest** [comment]
OK-阿阳
