### ISSUE TITLE
【pc chrome】首页 > 公告列表 > 发公告：维度为“ 单人／多人(6人)”时，提示设置对象

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#161]
![qq20180125-204822](https://user-images.githubusercontent.com/35476103/35389139-8126808a-0211-11e8-93b9-d9451e3c9c76.png)

**Comment by WWcodeTW** [comment]
要按"添加"加入用戶

**Comment by ruoktest** [comment]
已确认
