### ISSUE TITLE
金流记录页面，没有数据时弹出空提示。

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#166]
![image](https://user-images.githubusercontent.com/30371002/35467546-246bcf1c-0342-11e8-874e-6163a4874319.png)
此时api返回记录列表为空，不是错误。

**Comment by tonyisid** [comment]
这个是修改了过滤条件导致的，@205043957 改一下

**Comment by patrickkh7788** [comment]
默认点进去的选项，数据库没有数据记录。返回的page_items=0, 是不应该报错的。目前报错了。
