### ISSUE TITLE
试玩会员没有银行卡等记录！

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#168]
![image](https://user-images.githubusercontent.com/30371002/35468141-c0a7093e-034a-11e8-97ad-3f5a390bde17.png)

**Comment by patrickkh7788** [comment]
取款密码也没有。

**Comment by tonyisid** [comment]
这些地方都要删掉吗？

**Comment by patrickkh7788** [comment]
删掉！

**Comment by tonyisid** [comment]
fixed

**Comment by patrickkh7788** [comment]
![image](https://user-images.githubusercontent.com/30371002/35469539-169928cc-0369-11e8-8413-323e5c10a005.png)
![image](https://user-images.githubusercontent.com/30371002/35469542-27a1fd4c-0369-11e8-8515-86111b9820f3.png)

**Comment by tonyisid** [comment]
fixed
