### ISSUE TITLE
产品列表文字描述。

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#169]
![image](https://user-images.githubusercontent.com/30371002/35468417-b93c107c-034f-11e8-87ad-f8d6e0659378.png)

这里的开盘中与开盘应该修改为-》  已启用， 启用。 

开盘封盘是另外的概念，与这个转改无关。

**Comment by patrickkh7788** [comment]
PC前台显示的状态：  https://api.ruok.co/cn/cgi/api/current_issue_no?item_code=xglhc
可以根据 time （剩余秒数）来处理。
对香港六合彩来说， 在开奖后的一段时间内，如果上一期没有开出来，下一期是不能购买的。也就是自动封盘了。

**Comment by tonyisid** [comment]
我把文字改了
