### ISSUE TITLE
【阿阳-后台】股东层级权限错误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#171]
股东等层级没有后台直接新增帐号的权限。

股东权限已经全给了，但姓名无法查看有误
![a1](https://user-images.githubusercontent.com/35476103/35469433-34cfb182-0367-11e8-9628-115d30c21f26.jpg)

**Comment by patrickkh7788** [comment]
![image](https://user-images.githubusercontent.com/30371002/35469557-7c68b744-0369-11e8-8424-6b27546b672d.png)

@tonyisid  需要给股东授予 姓名的查看权限。

**Comment by ruoktest** [comment]
姓名    不给予股东层级可操作的权限选择性。  框直接用灰色

**Comment by tonyisid** [comment]
目前的逻辑是，真实姓名不给股东看，所以在权限配置那里没有真实姓名那一栏。

**Comment by ruoktest** [comment]
姓名不是机密，而是属于基础信息，是必须要给予查看的，

但操作修改姓名的性质就完成不一样。

**Comment by tonyisid** [comment]
@patrickkh7788 请确认！

**Comment by patrickkh7788** [comment]
@tonyisid 
我们有一个姓名的授权字段，不管他是否机密信息。 对姓名进行授权控制就需要允许股东对姓名进行（查看，操作的授权）

目前是子账号有姓名授权，股东没有。所以股东没有办法看见，添加股东姓名授权后，就可以对股东修改姓名以及查看姓名进行控制了。不然默认就是没有权限查看和修改。

**Comment by tonyisid** [comment]
目前除了运营商及子账号有姓名查看权限，其他的都没有。
是否要修改？

发自我的 iPhone

**Comment by patrickkh7788** [comment]
是

**Comment by tonyisid** [comment]
是只给股东，还是总代和代理都有？

**Comment by patrickkh7788** [comment]
都有。

**Comment by tonyisid** [comment]
fixed
