### ISSUE TITLE
【阿阳-后台】用户详情页面-取款金额报错-底部注单统计需要修改

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#175]
<img width="1279" alt="a1" src="https://user-images.githubusercontent.com/35476103/35479442-3ce2fcd0-042a-11e8-80ef-4081e57799a4.png">
<img width="1276" alt="a2" src="https://user-images.githubusercontent.com/35476103/35479443-3d13f95c-042a-11e8-8ac7-4c271b7c2dd1.png">
图一取款金额显示错误。

图二默认显示当天的投注情况，   并增加按钮   今天/昨天/本周/上周/本月 快捷查询。

同类问题还有：

https://github.com/ruoklive/lottery_bug/issues/92

https://github.com/ruoklive/lottery_bug/issues/7
   编号7这个问题至今没有解决，且 这个详情显示的是这个彩种的注单列表清单。   

https://github.com/ruoklive/lottery_bug/issues/157
这个是新增功能，至于是使用 TAP还是弹窗交由技术沟通。

**Comment by patrickkh7788** [comment]
今天/昨天/本周/上周/本月 快捷查询 数据格式！
![image](https://user-images.githubusercontent.com/30371002/35491888-008a8af2-04dc-11e8-9450-29d3e916acdc.png)

**Comment by ruoktest** [comment]
1-30阿阳复测：
操作流程-   点击交收汇总报表，时间段节点为昨天， 点击进入到相应的会员详情页面时，底部的注单统计时间未同步，  手工选择了本周之后，点击详情，又是显示的是当天。

**Comment by patrickkh7788** [comment]
@ruoktest 
从交收汇总报表跳转到 会员详情。  时间只有（ 今天  本周  上周  本月 ）四个固定时间段选择。没有昨天，而且时间段是前台控制的。

从会员详情跳转到订单的时间段选择，后台是已经支持了的。前台这里有跳转起来有点问题。 @tonyisid 正在研究解决方案中。

**Comment by tonyisid** [comment]
> 操作流程- 点击交收汇总报表，时间段节点为昨天， 点击进入到相应的会员详情页面时，底部的注单统计时间未同步， 手工选择了本周之后，点击详情，又是显示的是当天.

这个时间过滤条件是分页面的，不是全局查询时间，所以时间条件不会跟着页面走

**Comment by tonyisid** [comment]
目前只做到了在用户详情页跳转注单报表的时候带上时间参数。
可以复核一下。

**Comment by ruoktest** [comment]
2-8号复测，已使用其它方案代替。
