### ISSUE TITLE
【阿阳-后台】股东推广域名注册无效等问题！！！！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#176]
<img width="1279" alt="a2" src="https://user-images.githubusercontent.com/35476103/35479564-27e3846e-042d-11e8-9f9b-f1de40a41c98.png">
<img width="1279" alt="a4" src="https://user-images.githubusercontent.com/35476103/35479565-284588da-042d-11e8-8c4f-861722f5b256.png">
<img width="1236" alt="a5" src="https://user-images.githubusercontent.com/35476103/35479566-2875f510-042d-11e8-85ab-3b767e1adba9.png">

问题一：域名设置列表有问题，重复出现

问题二：使用默认的推广域名注册后，会员直接进入到运营商层级

**Comment by patrickkh7788** [comment]
>问题一：域名设置列表有问题，重复出现

已经修复！

> 问题二：使用默认的推广域名注册后，会员直接进入到运营商层级

在域名禁用的状态下，推广机制不起作用。另外有一个域名状态缓存优化的问题，已经修复。测试ruok2323推广以及上级设置正确。

**Comment by ruoktest** [comment]
1-29号，阿阳重检：一级跟踪能够做到位，  二级跟踪失败
即使用 ruok666.com 注册aruok1234 能登记到  cooboy名下，   
使用 aruok1234的推广域名  http://ruok666.com/?recommend_username=3babaa#reg  注册时，注册页面未并带出会员的推荐ID值，导致bruok1234直接进入股东，而与推荐会员失联。

**Comment by patrickkh7788** [comment]
@chansent 
注册的时候，需要把get里的recommend_username参数自动输入到推荐人输入框。

**Comment by chansent** [comment]
注册时添加自动获取get参数

**Comment by ruoktest** [comment]
1-31号 阿阳复检：http://ruok666.com/?recommend_username=3babaa#reg    推荐人传值有误，请修复。

**Comment by patrickkh7788** [comment]
![image](https://user-images.githubusercontent.com/30371002/35620319-674f5c08-06b3-11e8-95f1-438e8810b0cd.png)

**Comment by ruoktest** [comment]
2-1  复测，请及时修复此问题···！！！！！！

**Comment by chansent** [comment]
优化了正则逻辑，修复了此问题。

**Comment by ruoktest** [comment]
2-1号，复测：虽然注册页面跟踪到的推荐代码，但实际注册后，与会员推荐仍然没有关系！

**Comment by patrickkh7788** [comment]
@ruokco  如果测试失败，麻烦提供核验数据好方便快速核验。

这里测试使用 地址http://ruok666.com/?recommend_username=3babaa#reg注册 账户 redmi4， 上级ID为 1493 推荐人ID为1639。    数据库核对 推荐码3babaa用户正是1639，上级也正是1493。  与会员推荐正确建立关系。

**Comment by ruoktest** [comment]
经检测，会员中心可见下线，  后台用户列表没有显示，

<img width="1162" alt="a5" src="https://user-images.githubusercontent.com/35476103/35678963-e217e750-0787-11e8-92a6-6c5fffeb709d.png">
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35678964-e24ac256-0787-11e8-8d37-340f9414d42f.png">

**Comment by ruoktest** [comment]
<img width="1162" alt="a5" src="https://user-images.githubusercontent.com/35476103/35679291-10952bbe-0789-11e8-9e58-e2e7341a27bf.png">
会员前台推广中心，用户名需要隐密处理，中间为**不可见代替

**Comment by patrickkh7788** [comment]
文档里下线数量字段是recommend_users, UI这里需要调用recommend_users才可以正确显示下线数量。

**Comment by ruoktest** [comment]
2-2号复测未修复。

**Comment by ruokco** [comment]
backend-ui 2-5

**Comment by tonyisid** [comment]
2.5 已经改成 recommend_users 字段

**Comment by ruoktest** [comment]
2-8号复测，用户名加密重新提交，此文关闭。
