### ISSUE TITLE
【pc Safari】配置-财务-银行管理  和  配置-新闻管理 是同一个页面

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#182]
![6-1](https://user-images.githubusercontent.com/35476103/35479992-67cc914e-043f-11e8-8557-ea0cc9c999d8.png)
![6-2](https://user-images.githubusercontent.com/35476103/35479994-6f7a25d2-043f-11e8-874d-9485125274da.png)

**Comment by luispuentesvega** [comment]
It would be solve with the merge of the news page!
