### ISSUE TITLE
【后台】会员里的--详情--日志 里   登录用户名为空

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#184]
【后台】会员里的--详情--日志 里   登录用户名为空  
账号：qiau123

**Comment by patrickkh7788** [comment]
@tonyisid 
这里不需要显示用户名。

**Comment by patrickkh7788** [comment]
![image](https://user-images.githubusercontent.com/30371002/35492012-c24b07b6-04dc-11e8-8b3d-bccdea25370f.png)

**Comment by 205043957** [comment]
已改，是否需要显示登录位置？？
