### ISSUE TITLE
【pc Safari】配置-域名配置-停用/启用：提示文案为空，就一个感叹号

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#186]
![8](https://user-images.githubusercontent.com/35476103/35480315-52f510dc-0446-11e8-9b2e-8bbb8578aaf5.png)

**Comment by patrickkh7788** [comment]
已修复！

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/187
