### ISSUE TITLE
【pc Safari】[首页-用户组列表-配置用户组] 和 [配置-网站配置] 和 [客户端显示不一致]

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#188]
![7-1](https://user-images.githubusercontent.com/35476103/35480432-ab50415a-0448-11e8-8662-2a0c0abda54b.png)
![7-2](https://user-images.githubusercontent.com/35476103/35480433-ab864372-0448-11e8-94af-dabbe26a3eca.png)
![7-3](https://user-images.githubusercontent.com/35476103/35480434-abba9352-0448-11e8-8c65-332d9eb1b87f.png)

**Comment by patrickkh7788** [comment]
@ruoktest  前台显示的是可用提款额度，后台设置的是总额度。连个值不相等是正常的。

@huangjianguohjg @chansent 
amount_info api接口添加了一个新的字段, error. 如果最大提款额度为0, 这个error会给出错误信息，需要显示给用户。

**Comment by huangjianguohjg** [comment]
移动端这边调用的是withdrawals 限额是withdrawals接口返回额度限制
