### ISSUE TITLE
【阿阳-前台】注册页面判断有误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#189]
<img width="891" alt="a1" src="https://user-images.githubusercontent.com/35476103/35494750-53d512fa-04ef-11e8-9027-094279981335.png">
如图，提示用户名已存在，但用户在输入后，网站提示的是用户名可正常注册！！！！！！！

**Comment by chansent** [comment]
此处校验的是用户名是否符合输入规则，不是校验是否存在，所以输入的用户名是显示通过的。
目前我们没有单独校验某个用户名是否存在的接口，只有提交注册的时候由server返回失败原因。

**Comment by ruoktest** [comment]
需要增加判断，打绿勾就表示说这个用户名是合规则并且是可以注册的！

**Comment by patrickkh7788** [comment]
@chansent 
![image](https://user-images.githubusercontent.com/30371002/35542944-1e439bd8-0595-11e8-97f6-4cca1e1cfe4c.png)

**Comment by chansent** [comment]
已添加用户名是否存在的校验

**Comment by ruoktest** [comment]
<img width="1251" alt="a5" src="https://user-images.githubusercontent.com/35476103/35718367-b8e96bf8-0816-11e8-9f4f-07c58ff32820.png">
<img width="1051" alt="a6" src="https://user-images.githubusercontent.com/35476103/35718368-b9dbb5b6-0816-11e8-99ad-0896028a2efa.png">
投注大厅处的注册与首页点击注册页面，里面的规则要求应该保持一致。

**Comment by ruokco** [comment]
backend-ui 2-5

**Comment by chansent** [comment]
购彩大厅点击注册后现在跳转到注册页，后期可以再考虑重构购彩大厅的注册弹窗。
