### ISSUE TITLE
【阿阳-后台】用户详情页面，赔率演示功能不完整。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#190]
<img width="1279" alt="a2" src="https://user-images.githubusercontent.com/35476103/35495808-6184abee-04f5-11e8-917a-bdc046190226.png">

切换彩种，很多彩种的相对应赔率演示均未正常。

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-1号，阿阳复测，功能尚未完结，
初步查看传统的，定位球玩法丢失。

**Comment by ruoktest** [comment]
#193  这个问题查看也是丢失部分玩法。请复查。

**Comment by ruokco** [comment]
back-api 2.6
back-ui 2.7

**Comment by patrickkh7788** [comment]
@ruoktest 
请给出更详细信息。

**Comment by ruoktest** [comment]
2-8号复测OK
