### ISSUE TITLE
【阿阳-后台】帐号-会员列表-取款笔数，取款金额确认！十万火急········！！！！！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#192]
<img width="1279" alt="b1" src="https://user-images.githubusercontent.com/35476103/35496088-32580026-04f7-11e8-9f69-83adc32b9ae7.png">
这个帐号我新注册的，且只加了一笔 人工存款两千的，为什么列表这里会有显示取款 1 笔，2000呢。

**Comment by patrickkh7788** [comment]
这个是API错误，显示为入款了。已经修复。

**Comment by ruoktest** [comment]
阿阳复检OK
