### ISSUE TITLE
【阿阳-后台】配置-网站配置-自动返佣时间点问题。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#194]
<img width="1127" alt="a5" src="https://user-images.githubusercontent.com/35476103/35496851-5091918a-04fa-11e8-8343-c063e939cfbb.png">

<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35496906-8b7f05d4-04fa-11e8-8b39-2d77aef7a4e7.png">

这里的时间是以哪个时间区为依据。   北京时间还是服务器时间。

**Comment by patrickkh7788** [comment]
这个世界目前是固定的北京世界2：00。
后台任务目前php还不好控制，所以这个值没有使用。

**Comment by ruoktest** [comment]
2-1号阿阳与阿龙商定：返佣时间不可自定义，由平台商统一。
