### ISSUE TITLE
【阿阳】后台-帐户-用户名规则问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#196]
<img width="1279" alt="b1" src="https://user-images.githubusercontent.com/35476103/35500142-09296918-0508-11e8-93ec-46aca93a3362.png">

整站，不论级别，不论前后台，所有的帐号/用户名    均统一使用  只能包含数字字母下划线，下划线不能作为开头和结尾

**Comment by patrickkh7788** [comment]
这个是老得数据，目前后台是不允许创建汉字或者符号用户名的。
