### ISSUE TITLE
【阿阳-前台】会员个人中心无法绑定真实姓名！！！！！······

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#199]
<img width="1239" alt="a5" src="https://user-images.githubusercontent.com/35476103/35503014-754d457a-0511-11e8-9c60-fd8205ea2807.png">

<img width="1060" alt="a6" src="https://user-images.githubusercontent.com/35476103/35503015-75896960-0511-11e8-8f47-94667a868530.png">

用户注册时，第一时间不需要填写真实姓名，但需要他在充值的时候就检测，如果姓名不存在，则提醒并跳转到个人中心完成 资金密码以及银行卡的绑定。

问题二：目前个人中心绑卡里面，需要增加一个判断，如果真实姓名不存，则开放自定义姓名，如果已经存在，则锁定姓名！

问题三：点击绑卡操作时，先检测资金密码，不存在时弹出提醒并跳转

**Comment by ascar5** [comment]
这个算新feature了  需求已确认 前端不清楚可以找我确认

**Comment by chansent** [comment]
完成功能开发

**Comment by ruoktest** [comment]
2-1号复测：使用帐号  cruko1234  密码：112233qq  
问题一：使用苹果SAFARI，在设置密码时，姓名莫名调出  aruok1234,切换回谷歌浏览器又是空白正常状态。

问题二：输入姓名密码，第一次设置密码竟然提示我验证码错误了。

<img width="1214" alt="a7" src="https://user-images.githubusercontent.com/35476103/35679271-fa74d712-0788-11e8-92ea-34855658ce3e.png">
<img width="1065" alt="a8" src="https://user-images.githubusercontent.com/35476103/35679272-faa5afae-0788-11e8-9ba0-f7bff27831b5.png">

**Comment by WWcodeTW** [comment]
@chansent 设置资金密码 是用set_withdraw_password

**Comment by WWcodeTW** [comment]
设置资金密码set_withdraw_password参数{ withdraw_realname, new_password, comfirm_password  }
修改资金密码change_withdraw_password参数{password, new_password, comfirm_password }

**Comment by ruokco** [comment]
PC-ui 2-5
PC-API document need to update 2.5

**Comment by ruoktest** [comment]
2-6号复测  OK
