### ISSUE TITLE
【阿阳-后台】交收汇总报表结果有误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#202]
<img width="1278" alt="a5" src="https://user-images.githubusercontent.com/35476103/35553553-eb0b1238-05ca-11e8-8953-d6c10c47cd69.png">

本报表查的是 1-29号的，即昨天的报表，

疑惑一：会员返佣，当天下注没有统计，而是等到第二天实际返还之后再显示，那么相当于，当天后台的实际赢利无法准确得知！！！   需要重新论证一下这个问题。

问题二：如图  cooboy这个股东，本级佣金我也没有搞明白他的钱是哪来的。即找不到明确的佣金设立点

问题三：会员最终只是输了  40块钱，   为什么运营商能赚到 80块钱呢？？？？？

**Comment by patrickkh7788** [comment]
> 问题二：如图 cooboy这个股东，本级佣金我也没有搞明白他的钱是哪来的。即找不到明确的佣金设立点

会员针对cooboy这个股东，针对传统北京赛车设置所以利润都给了股东。
![image](https://user-images.githubusercontent.com/30371002/35561983-8903e82a-05e4-11e8-861b-e0bfb63a0a00.png)
这个利润百分比我们在老后台写的是“上级利润百分比”。
所以赢的钱除了给会员返水之外，全部给了股东。也就是40元。

> 问题三：会员最终只是输了 40块钱， 为什么运营商能赚到 80块钱呢？？？？？

这里的80元是只是统计输赢，返水没有参与计算。

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/207

**Comment by patrickkh7788** [comment]
![image](https://user-images.githubusercontent.com/30371002/35912904-8960a6ee-0c30-11e8-93f0-1da2c6d190ae.png)
点击金额跳转后，需要传入参数by_update=1.  

@ruoktest 跳转后是否需要显示处理时间？
