### ISSUE TITLE
【阿阳-后台】新增会员不需要权限密码验证

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#203]
新增会员不需要权限密码验证

并请把权限密码也提供一下，方便验证

**Comment by patrickkh7788** [comment]
后台只在修改开户名（用户姓名），并且已经保存用户姓名不为空的情况下要求权限验证。
这里弹出的权限验证可以随便输入因为后台不会去做验证。 @tonyisid 去掉这里的验证，并且只在修改开户名（默认的不为空）的情况下进行验证。


默认密码是 123456. 可以在个人中心修改。

**Comment by tonyisid** [comment]
> 后台只在修改开户名（用户姓名），并且已经保存用户姓名不为空的情况下要求权限验证。
> 这里弹出的权限验证可以随便输入因为后台不会去做验证。 @tonyisid 去掉这里的验证，并且只在修改开户名（默认的不为空）的情况下进行验证。
才加的权限密码验证，确定要去掉吗？

**Comment by ruoktest** [comment]
新增用户以及第一次输入姓名时，不需要权限验证， 二次修改用户的姓名时才需要验证。

**Comment by tonyisid** [comment]
fixed
