### ISSUE TITLE
【阿阳-后台】会员注单列表需要增加期数显示

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#204]
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35555722-b17ae766-05d2-11e8-83c6-7f92dce59836.png">

如上图，没有相应的期数，无法直观参考，需要增加。

且当进入详情注单页时，点总报表无效。

**Comment by tonyisid** [comment]
且当进入详情注单页时，点总报表无效。
具体操作是怎样？

**Comment by patrickkh7788** [comment]
@tonyisid 期号已经在API里。

> 且当进入详情注单页时，点总报表无效。

这个bug我在其他地方也碰到过。就是在特定的页面，有一部分导航栏点击没有反应。
![image](https://user-images.githubusercontent.com/30371002/35565246-617b7dd0-05ef-11e8-9518-49e48a5e715f.png)

**Comment by tonyisid** [comment]
1. 期号已经增加
2.跳转问题解决
