### ISSUE TITLE
投注详情

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#206]
![image](https://user-images.githubusercontent.com/30371002/35603142-74a19082-066e-11e8-8c51-8af4affa6709.png)
![image](https://user-images.githubusercontent.com/30371002/35603182-a72b5510-066e-11e8-81a1-73cae6e6bf56.png)
赔率返水应该是 ：
![image](https://user-images.githubusercontent.com/30371002/35603220-d3a68358-066e-11e8-8052-a5beacd5dbb1.png)

**Comment by tonyisid** [comment]
fixed
