### ISSUE TITLE
【阿阳-后台】交收汇总报表文字以及位置调节

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#207]
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35607480-e05ac2a4-0686-11e8-8b47-4506131c5293.png">

平台输赢    改为   输赢

会员还水以及 会员总计  移动到  输赢   后面

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
<img width="1278" alt="a7" src="https://user-images.githubusercontent.com/35476103/35622814-bb657860-06bb-11e8-9840-5ed02ca23e71.png">


  红色框内  输赢一栏的值 正负/颜色   应该与  会员总计保持一致。


同时公式也需要修改：    输赢+返水  =  会员总计，    尾部的公式如果需要也请同时变更。

**Comment by ruoktest** [comment]
<img width="1276" alt="a5" src="https://user-images.githubusercontent.com/35476103/35763720-bd577a9e-08e4-11e8-8a34-553d6e8a928f.png">

交收汇总报表底下的统计栏也需要进行位置调节，   同时注意：平台输赢这栏的  颜色跟正负状态需要修改成 会员总计一致！

**Comment by ruokco** [comment]
backend-ui 2.5

**Comment by tonyisid** [comment]
平台输赢 不是跟会员总计是相反的吗？

**Comment by ruoktest** [comment]
这里的颜色目前实现的对的，不用改了

**Comment by ruoktest** [comment]
2-6号阿阳复检：  底部的区域还没有完全调整，

https://user-images.githubusercontent.com/35476103/35763720-bd577a9e-08e4-11e8-8a34-553d6e8a928f.png


交收汇总报表底下的统计栏也需要进行位置调节， 同时注意：平台输赢这栏的 颜色跟正负状态需要修改成 会员总计一致！

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-8阿阳复测OK
