### ISSUE TITLE
【阿阳-后台】报表金额点击调节为 当前页面 (交收汇总报表) 新增tab(如图2)

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#208]
<img width="1277" alt="a7" src="https://user-images.githubusercontent.com/35476103/35607520-23ae4e04-0687-11e8-939e-f2d3aadd37ca.png">

点击   下注金额以及  有效金额时，弹出浮动层显示相应的列表。

**Comment by ruoktest** [comment]
![default](https://user-images.githubusercontent.com/35476103/35659107-062bc2f2-0737-11e8-9951-a0190bccbd46.jpg)

**Comment by tonyisid** [comment]
这样交收报表里面就会存在4种tab，总报表、会员报表、股东的交收报表、股东（会员）的注单报表。
而且交收报表的查询之前是没有注单号的。

**Comment by ruoktest** [comment]
表头筛选选项应该还是交收报表的选项。我修改一下设计稿

**Comment by ruoktest** [comment]
![default](https://user-images.githubusercontent.com/35476103/35667258-906f2fc6-075f-11e8-8ebe-6948d0264b84.jpg)
筛选条件依然是交收汇总报表的条件。
页面所有的筛选条件不应该针对这个新增的tab。这个TAB只是查看而已。

**Comment by tonyisid** [comment]
已经增加了tab

**Comment by ruoktest** [comment]
2-8号复测OK
