### ISSUE TITLE
【阿阳-后台】新增股东层有用户，默认盘口利润比设置

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#210]
新增股东层有用户，默认盘口利润比设置  要与   产品配置中心的留水百分比一致〜！

**Comment by patrickkh7788** [comment]
新增股东，需要调用： http://admin/cn/api/user/create?user_type_id=1    这里的games.percent就是默认值。目前显示的是0 。

**Comment by tonyisid** [comment]
目前已经是绑定了games.percent，显示的也是0

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-2复测OK
