### ISSUE TITLE
新增用户，银行下拉列表！

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#212]
![image](https://user-images.githubusercontent.com/30371002/35612757-88d5c202-069c-11e8-9c5d-25b158ae0a26.png)

这里应该是下拉列表给用户选择。 在api user_create 里有银行列表提供选择。

**Comment by tonyisid** [comment]
那传入参数withdraw_bankname 是传名称还是bank_id?

**Comment by tonyisid** [comment]
我还是传bankname了

**Comment by patrickkh7788** [comment]
bank_id

**Comment by ruoktest** [comment]
已验证通过
