### ISSUE TITLE
【阿阳-后台】帐号-会员-新增失败！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#213]
<img width="1279" alt="a7" src="https://user-images.githubusercontent.com/35476103/35614929-4176aa50-06a3-11e8-9d01-fc16c84b16e4.png">

新增会员，用户组选择失败

新增直属会员，用户组选择功能丢失！！！！！！！！

**Comment by ruoktest** [comment]
这个问题请及时修复，否则无法完成后续测试工作。

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-2号复测：
新建会员OK
新建直属会员提示    不能是前台类弄，但实际已经建立成功
<img width="924" alt="a5" src="https://user-images.githubusercontent.com/35476103/35717598-f0f4e8c8-0812-11e8-90f2-40774a26ebdf.png">

**Comment by patrickkh7788** [comment]
@tonyisid 
保存直属用户为什么要调用 agent_auth ？

**Comment by tonyisid** [comment]
前端少了一个直属用户的判断，我加上

**Comment by ruoktest** [comment]
2-3号复测，使用苹果   safari  帐号管理内：新增会员，新增代理等均点击无效。
#222

**Comment by ruokco** [comment]
need to confirm backend-UI 2.5

**Comment by ruoktest** [comment]
2-7号复检无问题
