### ISSUE TITLE
【阿阳-后台】存取款流程有误以及相关连错误·····！！！！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#214]
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35620483-df139074-06b3-11e8-847b-7d3b3cfcfc9c.png">
上图是在等待出款，操作之前做的截图

<img width="1279" alt="a5" src="https://user-images.githubusercontent.com/35476103/35620630-4c7f1cc8-06b4-11e8-88c2-62b9d09fa7a6.png">
这是存取款中心，看不到纪录， 针对性查  972428057   这个用户，也没有看到。

<img width="1274" alt="a7" src="https://user-images.githubusercontent.com/35476103/35620690-760b7fd2-06b4-11e8-98fd-2247ea11acb4.png">
首页新增的   存取款汇总    数据统计有误！！！！

连带发现问题：顶部的几个出入款申请数量标识，如图 出款审核，原来就有 17个，我通过了一个，实际上应该是     即时出款  显示  16          等待出款  显示  1     才对。    顶部的数据不论运营商停在哪个页面，都是实时调用的，有多少就显示多少···！！！！！！

**Comment by ruoktest** [comment]
<img width="1277" alt="a7" src="https://user-images.githubusercontent.com/35476103/35621081-b1edd86e-06b5-11e8-98a2-c4ae0d8f6f82.png">


同时修改一下文案      出款时间    改成   申请时间    

将   审核时间     与   出款时间     的位置互换

**Comment by patrickkh7788** [comment]
> 上图是在等待出款，操作之前做的截图
> 这是存取款中心，看不到纪录， 针对性查 972428057 这个用户，也没有看到。

在存取款列表，API文档有列出有一个确认时间（等待出款确认）以及审核时间（即时出款审核），在等待出款里确认出款后这条记录更新的是确认时间不是审核时间。 所以你按照审核时间排序是看不到的。UI可以加上显示确认时间以及排序功能就可以方便查看。 （API已经支持）
![image](https://user-images.githubusercontent.com/30371002/35622864-f8fbbf40-06bb-11e8-8af7-1c6753b16cbb.png)

> 首页新增的 存取款汇总 数据统计有误
本日汇总数字是显示错误的，已经修改了。 还有其他错误的话请说明是那个数字错误。


>连带发现问题：顶部的几个出入款申请数量标识，如图 出款审核，原来就有 17个，我通过了一个，实际上应该是 即时出款 显示 16 等待出款 显示 1 才对。 顶部的数据不论运营商停在哪个页面，都是实时调用的，有多少就显示多少···！！！！！！

这个需要UI在审批以及拒绝的时候直接更改相应数字，或者调用接口更新数字。

**Comment by ruoktest** [comment]
存取款纪录这里的出款审核时间，要以等待出款的通过时间为依据，   不能调用    即时出款 时的审核时间。

图中 -304   -366   均为 31号晚上操作的，但审核时间调用错误了。

**Comment by ruoktest** [comment]
<img width="1278" alt="a8" src="https://user-images.githubusercontent.com/35476103/35623566-a08af99a-06be-11e8-9f77-6ec242bbf389.png">

这里我是直接通过查询   972428057    默认一个月的状态，但同样没有看到在队列当中。

**Comment by patrickkh7788** [comment]
> 存取款纪录这里的出款审核时间，要以等待出款的通过时间为依据， 不能调用 即时出款 时的审核时间。
图中 -304 -366 均为 31号晚上操作的，但审核时间调用错误了。

审核时间与确认时间是两个不同的时间，如果要以“待出款的通过时间” 就需要增加一个确认时间的表格栏目。
如果使用确认时间作为这里的审核时间，就不能进行按照混合时间排序（单独确认时间或者单独审核时间都可以排序，但是混合审核与确认时间就无法排序了）。

![image](https://user-images.githubusercontent.com/30371002/35623776-5e4270e4-06bf-11e8-9fbb-e90db11a7fb3.png)

**Comment by HangZyc** [comment]
@ruoktest @patrickkh7788 @ruokco 

关于首页存取款数据说明：已经核对过，页面UI 展示数据跟接口返回数据一致，需要 check 下接口的返回是否正确；

关于顶部数据更新问题：目前数据更新没有跟页面内 UI 操作关联，固定每 5 min 自动拉取最新数据。

**Comment by ruoktest** [comment]
顶部自动拉取时间间隔必须要短，五秒或者十秒左右，能做到实时变化最好。

**Comment by tonyisid** [comment]
存取款操作会动态获取task数据，更新顶部数字

**Comment by ruoktest** [comment]
2-8号复测，此问题主要还是 时间区段的问题，已经更新为以确认时间为依据。
