### ISSUE TITLE
【阿阳-后台】所有的后台提示框显示需要优化以及    等待出款功能需优化。  

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#215]
<img width="1275" alt="a7" src="https://user-images.githubusercontent.com/35476103/35621227-3a553184-06b6-11e8-9209-218b25e8c351.png">

这里的复制成功弹窗提示占用的时间太久了，后台出款人员复制粘贴练的话，会在这里浪费很多的时间，需要进行优化

引发的问题：以前在开发时说过，这个等待出款界面，一旦用户点击了任意一个地方，那么整栏应该强化突出显示。

如点击  谢婷丽    这栏的任意一个地方，那么整栏高亮突出显示， 其它栏则小灰色，直至用户点击  出款或者异常      若用户点击本栏以外的地方，提醒用户是否取消该栏的选择。
#214

**Comment by ruoktest** [comment]
<img width="1240" alt="a8" src="https://user-images.githubusercontent.com/35476103/35621748-0e9dcc0c-06b8-11e8-9950-16f4cbd8c416.png">

如上图所示，    出款方式   这个名称的定义，目前是写的人工，具体是指的  人工提交的取款请求（如果是这个的话，可以将文案修改成   在线取款），还是说运营商给客户出款的方式是人工呢？

这个审核界面所要实现的目标不是很明确，
存款金额    优惠金额     投注金额（且投注金额要调用   有效金额·！）    这几个项目均要能点击，并以  弹出层的形式将数据直观的体现出来。



最后  底下的最近投注，   赢钱有统计，输钱则显示为零，容易造成未结算的状态。

**Comment by tonyisid** [comment]
请确认是否这样修改！

**Comment by ruoktest** [comment]
是的，可以按这样修改。

**Comment by tonyisid** [comment]
1. toast现在改成点击屏幕后关闭，或者5秒后关闭
2. 已经修改了相关字段。
3. 这个详情页已经是弹出页面，不好在该页面上再弹出页面。看看能有其他方法解决吗

**Comment by ruoktest** [comment]
引发的问题：以前在开发时说过，这个等待出款界面，一旦用户点击了任意一个地方，那么整栏应该强化突出显示。

如点击 谢婷丽 这栏的任意一个地方，那么整栏高亮突出显示， 其它栏则小灰色，直至用户点击 出款或者异常 若用户点击本栏以外的地方，提醒用户是否取消该栏的选择。

这个等待出款界面没有实现选择行高亮显示。


#222      即时出款页面打不开，无法查验，

**Comment by ruoktest** [comment]
顶部出入款几个页面无法点击，无法进入到页面

**Comment by ruokco** [comment]
高亮突出显示 UI- design need to confirm 
跟进下 顶部出入款几个页面无法点击，无法进入到页面 
2.5

**Comment by ruoktest** [comment]
2-4号，阿阳备注，整行高亮此要求可暂停，

**Comment by ruokco** [comment]
顶部出入款几个页面无法点击，无法进入到页面 跟进
