### ISSUE TITLE
remove rebate time setting from admin panel.

### ISSUE THREAD

**Issue by patrickkh7788** [ruoklive/lottery_bug#218]
@luispuentesvega 

![image](https://user-images.githubusercontent.com/30371002/35666674-88b113dc-075d-11e8-8579-f9444041dfce.png)

@codeistalk also need remove is_auto_rakeback auto_rakeback_time from api.

**Comment by luispuentesvega** [comment]
The change on frontend  has been done in the Pull Request "Fix bug 218"
