### ISSUE TITLE
【阿阳-后台】运营商后台修改用户姓名

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#219]
<img width="1026" alt="a5" src="https://user-images.githubusercontent.com/35476103/35679395-738cca38-0789-11e8-9206-4235401f675a.png">
修改姓名是需要验证权限密码的，

但目前没有可以输入密码的地方···！！！

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-2号复测OK
