### ISSUE TITLE
【阿阳-后台】用户详情页面-交易数据/   存取款纪录  报错

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#221]
<img width="1273" alt="a5" src="https://user-images.githubusercontent.com/35476103/35718513-82f12382-0817-11e8-8d56-fc2c3f8df1b6.png">

下图为   存取款纪录报错
<img width="1272" alt="a6" src="https://user-images.githubusercontent.com/35476103/35719062-fdf880e6-0819-11e8-983f-7efdf4acabc3.png">

**Comment by tonyisid** [comment]
@patrickkh7788 加一下review_time的排序条件

**Comment by patrickkh7788** [comment]
这个条件去掉了，nick在改。
