### ISSUE TITLE
【后台chrome 】首页 > 产品设置列表 > 传统北京赛车：平台利润，流水数据填写不对时，toast提示源码

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#227]
![1](https://user-images.githubusercontent.com/35476103/35763847-4baf4622-08f0-11e8-88d3-62233e713a67.png)

**Comment by ruokco** [comment]
backend-api 2.8

**Comment by patrickkh7788** [comment]
@tonyisid  UI逻辑混淆了我的流水百分比与本级留水。 请参考： https://admin.ruok.co/cn/topset/pro_odds/48  
child_profit 传入后台的值是错误的。

**Comment by tonyisid** [comment]
麻烦解释一下？

**Comment by tonyisid** [comment]
fixed
