### ISSUE TITLE
【后台】域名配置，通过域名地址+时间筛选时，域名地址取的是：filters":{"username":"www.qwqw.com"},"

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#228]
![2](https://user-images.githubusercontent.com/35476103/35764002-ea5bc406-08f2-11e8-90a3-69fbc0f5e0a7.png)

**Comment by 205043957** [comment]
你这边选的是账号，就是账号为  www.bixxx

**Comment by 205043957** [comment]
![image](https://user-images.githubusercontent.com/18372025/35765981-b590eff8-0901-11e8-8b8b-dde18ed5a7f5.png)

**Comment by tonyisid** [comment]
这个是正确的把？
