### ISSUE TITLE
【pc chrome】公司入账申请页-查看，该页面入款方式未显示

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#23]
![wx20180117-081030](https://user-images.githubusercontent.com/35476103/35021595-8a838124-fb6c-11e7-8b28-7d93ceb21a1d.png)

**Comment by tonyisid** [comment]
已经修复

**Comment by ruoktest** [comment]
修复后存在一个问题，当银行卡存在多个时，如何定位到客户是存入到哪一个名下呢

**Comment by patrickkh7788** [comment]
```json
{
"getbank": {
"name": "中国交通银行 福建分行 - 杨二",
"banckname": "中国交通银行 福建分行",
"bank_son": "福建分行",
"realname": "杨二",
"card_no": "6230780100010738403"
},
"bank_card_id": 6,
"card_type": "银行汇款"
}
```

在列表页以及详细页都有这几个字段，getbank的信息就是用户存入了那个银行了。这个至少要在详细页面展示，列表页最好可以以浮动层的方式或者其他方式展示。
