### ISSUE TITLE
【后台 Chrome】首页 > 第三支付管理 > 新增第三方支付：缺少“channel”

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#230]
![3](https://user-images.githubusercontent.com/35476103/35764073-69ee2258-08f4-11e8-9c1b-4319680681b6.png)

**Comment by patrickkh7788** [comment]
添加和编辑一样，留空没有办法保存的。 payment_channel_types

**Comment by tonyisid** [comment]
fixed
