### ISSUE TITLE
【后台 chrome】添加新闻分类成功的提示文案不妥，和修改新闻分类名字成功的文案是一样的

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#231]
![4](https://user-images.githubusercontent.com/35476103/35764150-e2716824-08f5-11e8-8604-4ce10e7e6d06.png)

**Comment by patrickkh7788** [comment]
after add newscate,  the msg should be "添加新闻分类完成".
after save modify newscate,  the msg should be "修改新闻分类完成".

**Comment by codeistalk** [comment]
The confirmation message is coming from UI, it's not the one which is provided by API.

**Comment by ruokco** [comment]
backend-ui 2.5

**Comment by luispuentesvega** [comment]
Solved in the P.R 'Fix bug 231 #10'
