### ISSUE TITLE
【后台 chrome】首页 > 用户组列表 > 编辑用户组：创建用户组提示源码

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#233]
![5](https://user-images.githubusercontent.com/35476103/35765228-c3dea67e-08fa-11e8-8797-a0aba1c1af8c.png)

**Comment by patrickkh7788** [comment]
@tonyisid 需要在创建时候传入设置返点的参数。

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已验证
