### ISSUE TITLE
【阿阳-后台】用户详情页面，金流纪录，途径显示不精准

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#237]
<img width="1279" alt="a5" src="https://user-images.githubusercontent.com/35476103/35767043-cbed1ab4-0916-11e8-9a3b-4c9389b383c3.png">

应当区分清楚是在线存款，还是人工存款

在线存款为用户登陆帐号自己提交的公司入款存款请求

人工存款为运营商后台为用户增加的金额。

**Comment by ruokco** [comment]
backend-ui 2.5

**Comment by patrickkh7788** [comment]
使用 transfor_type

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-8复测OK
