### ISSUE TITLE
【阿阳-后台】公司入款申请列表入款方式显示有误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#238]
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35767087-a98b8d1a-0917-11e8-8ffd-eb66d401200f.png">

会员  cruko1234     第一笔已确认金额   存款  222    这笔交易为人工存款，补的是存款-银行卡     那么这里的入款方式应该显示为   人工存款     

<img width="1203" alt="a7" src="https://user-images.githubusercontent.com/35476103/35767104-2a81e18a-0918-11e8-83c2-a438918830a2.png">

点击入款列表尾部的查看按钮进入会员存款纪录页面。
入款方式同样描述不准确，   
点击详情，无法调用页信。

**Comment by ruokco** [comment]
backend-api 2.8

**Comment by patrickkh7788** [comment]
使用 transfer_type

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
2-8复测OK
