### ISSUE TITLE
【pc chrome】公司入账申请页-查看，该页面导出CSV不成功

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#24]
![wx20180117-082333](https://user-images.githubusercontent.com/35476103/35021642-b9ed40f8-fb6c-11e7-9fd8-3cf07421b5dc.png)

**Comment by tonyisid** [comment]
很多页面还没有加导出功能，现在可以一步一步加

**Comment by tonyisid** [comment]
这个页面已经加上了

**Comment by ruoktest** [comment]
已验证
