### ISSUE TITLE
【阿阳-PC】提款金额限制调节无效。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#240]
<img width="1119" alt="a5" src="https://user-images.githubusercontent.com/35476103/35776577-a8a2be40-09d1-11e8-9da4-827479fa553d.png">
<img width="1142" alt="a6" src="https://user-images.githubusercontent.com/35476103/35776582-bc45ce4c-09d1-11e8-94a4-47101f72b074.png">

如图所示，后台用户组提款最大金额已调，但首页无更新，

**Comment by ruoktest** [comment]
<img width="975" alt="a7" src="https://user-images.githubusercontent.com/35476103/35776593-f0c78e12-09d1-11e8-9614-81730e3d3b6e.png">

**Comment by chansent** [comment]
@ascar5 数据来源是amount_info接口

**Comment by ascar5** [comment]
后台设置时 缓存未更新

**Comment by WWcodeTW** [comment]
緩存位置錯誤，已修復

**Comment by ruoktest** [comment]
<img width="1144" alt="a5" src="https://user-images.githubusercontent.com/35476103/35842164-083e0f6e-0b33-11e8-9a31-c123cbb9981d.png">
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35842165-088d0862-0b33-11e8-8c4b-6aaa2ad55765.png">
取款限额与后台无一用户组是匹配的。

当前登陆用户今天没有存取过款项，


BY阳

**Comment by ruoktest** [comment]
#255    与此问题相关，故将此问题关闭
