### ISSUE TITLE
【pc chrome】公司入账申请页-查看，页面跳转问题需确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#25]
1、右下角没有“跳转”按钮，但按Enter键可以跳转，是否需要天假跳转按钮？

2、输入页码超出范围后，按Enter键没有反应，是否需要提示文案？

![wx20180117-082245](https://user-images.githubusercontent.com/35476103/35021822-ae665af2-fb6d-11e7-8067-efde762bdc21.png)

**Comment by tonyisid** [comment]
1. 根据UI，没有跳转按钮。
2. 我统一加上提示文案。

**Comment by tonyisid** [comment]
提示文案已经加上

**Comment by bihuademon** [comment]
功能上，回车Enter即跳转哈～
