### ISSUE TITLE
【阿阳-PC端-后台】北京赛车每天最后一期/赔率的问题。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#250]
<img width="1279" alt="-6-" src="https://user-images.githubusercontent.com/35476103/35792818-9388e7e0-0a81-11e8-9b7d-eb16c81a472b.png">
<img width="1279" alt="-7-" src="https://user-images.githubusercontent.com/35476103/35792820-93bd9d82-0a81-11e8-8895-a08629c87068.png">
<img width="1279" alt="-8-" src="https://user-images.githubusercontent.com/35476103/35792821-93f0a9de-0a81-11e8-95fa-e3851d11df38.png">

图一是截自其它网站的，  北京赛车     昨晚最后一期    2018-02-04 23:57:30 | 665488     是有结果的，

但我们系统是处于没有结果的状态，需要重新对最后一期进行查证优化，否则会造成当天结算注单报表的计算有误问题。

最后一张图片显示的是封盘之后，系统显示的赔率异常。

**Comment by ascar5** [comment]
这个和issue 271 应是一个原因导致的  目前已修复   最后一期的情况 可以今晚复查一下

**Comment by ruoktest** [comment]
2-8号阿阳复测OK
