### ISSUE TITLE
【阿阳-后台】顶部黑色导航及内容页面刷新问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#257]
顶部的黑色导航自动刷新时间设置为十秒。

<img width="1279" alt="a5" src="https://user-images.githubusercontent.com/35476103/35847027-89fdfba0-0b4b-11e8-8cef-1af7ece86459.png">
<img width="1264" alt="a6" src="https://user-images.githubusercontent.com/35476103/35847051-95148f72-0b4b-11e8-98c4-9046c03a5c50.png">

问题一：当处于出入款审核页面时，前台用户再次提次请求，后台页面没有实现自动更新。

问题二：当客服处于查看审核页面时，数据刷新不能影响到他的操作。

问题三：审核页面的输赢结果一栏有问题。

问题四：最近出款金额       出款时间        历史出款等细节丢失

**Comment by patrickkh7788** [comment]
> 最近出款金额 出款时间 历史出款等细节丢失

已经修复。

**Comment by tonyisid** [comment]
已经加入轮询
输赢结果一栏修复

**Comment by ruoktest** [comment]
2-8号复测，   页面自动刷新机制仍未实现。

**Comment by tonyisid** [comment]
部署有10分钟延迟，请再复测一次

**Comment by ruoktest** [comment]
复测OK
