### ISSUE TITLE
【后台】注册用户数不正确

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#27]
1、早上11点注册了一个免费试玩的用户：用户号为：Guest1001462
2、在后台查不到该注册用户数，（因考虑可能不是，时时同点数据，所以特别意在下午2点左右的时间点查看注册用户数）

**Comment by patrickkh7788** [comment]
免费试玩会员和会员不一样，免费试玩会员的统计字段是  today_new_users.test_users， UI设计里没有要在首页显示试玩会员所以看到的数字是0.

**Comment by ruoktest** [comment]
确认
