### ISSUE TITLE
【阿阳-PC端】传统北京赛车游戏玩法BUG···！！！！极度优先

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#271]
<img width="1244" alt="a5" src="https://user-images.githubusercontent.com/35476103/35857736-9a721568-0b6c-11e8-9888-be1257654567.png">
<img width="1279" alt="a6" src="https://user-images.githubusercontent.com/35476103/35857764-b0aca96a-0b6c-11e8-9e50-e177929b5dbb.png">

问题一：北京赛车开奖异常。导致封盘，    
问题二：若封盘赔率统一不显示，或者统一显示，不应该出现部分赔率丢失。

**Comment by ascar5** [comment]
已修复

**Comment by ruoktest** [comment]
2-8阿阳复测，OK
