### ISSUE TITLE
【阿阳-APP】传统北京赛车手机端玩法错误···！！！优先处理

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#272]
![app11](https://user-images.githubusercontent.com/35476103/35857972-50882fb8-0b6d-11e8-910e-1dc220d16b61.jpeg)

手机端-传统北京赛车，冠亚组合内部错误。

问题一：不存在   冠亚和     这个玩法，    
问题二：冠亚军和值玩法丢失。

和值即   3到  19这个玩法，

冠亚军和值这个玩法放到   冠亚组合   这个玩法内部的顶部。

问题三：同时一并处理     冠亚大    冠亚小  冠亚单     冠亚双     冠亚大双   冠亚大单     冠亚小双    冠亚小单      为并列关系，（目前是一个玩法占据一个空行）

**Comment by ascar5** [comment]
已修复

**Comment by ascar5** [comment]
问题一二已解决 问题三涉及到后端改数据结构  这个需要三端都做调整  如果不是非必要 建议下版修改
