### ISSUE TITLE
帐户-> 股东/总代理/代理/会员->里面多出滚动条

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#30]
![default](https://user-images.githubusercontent.com/35476103/35029215-77a8a636-fb8c-11e7-9e34-816d5b6766da.png)

**Comment by tonyisid** [comment]
1.是否没有刷新网页
2. 系统环境是什么，mac ？ windows ？ chrome？ firefox？

**Comment by 205043957** [comment]
![image](https://user-images.githubusercontent.com/18372025/35033366-fdbbe3c2-fb9c-11e7-8a00-38c34485fd48.png)

**Comment by 205043957** [comment]
我这边用的 chrome 也能看到多了滚动条

**Comment by tonyisid** [comment]
是windows下的chrome有这个问题，我已经改好了。

**Comment by ruoktest** [comment]
已验证
