### ISSUE TITLE
【立即修复】编辑股东，提示  聊天室不存在    请立即修复··！

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#305]
<img width="1079" alt="a5" src="https://user-images.githubusercontent.com/35476103/36010957-b282feee-0d86-11e8-9a55-9a526c3c641e.png">

编辑股东盘口时提示   聊天室不存在     

估计是新增的功能未全面完成，优先修复此问题，需要测盘口设置·！

**Comment by tonyisid** [comment]
fixed.

**Comment by ruoktest** [comment]
OK
