### ISSUE TITLE
【ios】客户端登录输入密码时新包没有进行隐藏处理

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#32]
![d30a5e50af65a73d5209654d3dfe9583](https://user-images.githubusercontent.com/35476103/35037027-1e0cfddc-fbb1-11e7-800a-f6dc22127b27.png)

**Comment by huangjianguohjg** [comment]
已经隐藏
![281516186800_ pic](https://user-images.githubusercontent.com/19162597/35039441-6cccd68c-fbb0-11e7-9972-c772525351b7.jpg)
