### ISSUE TITLE
【Olivia-后台】配置-财务设置UI：排版没对齐

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#327]
1. 应该在一行的，其他tab也有此问题 请一起改了
![image](https://user-images.githubusercontent.com/35476103/36030366-7956992a-0dd9-11e8-86b6-ca306cac500b.png)

2. 当前实现的错位了
![image](https://user-images.githubusercontent.com/35476103/36030368-7faf7e7c-0dd9-11e8-9267-c0b39668f362.png)

3. 当前实现的总编辑里启用和删除的btn颜色用反了
![image](https://user-images.githubusercontent.com/35476103/36030355-717adcac-0dd9-11e8-88d6-47fa45d43c02.png)

4. 太贴边了，请给点距离，和全选的勾选项对齐
![image](https://user-images.githubusercontent.com/35476103/36030328-538f8850-0dd9-11e8-995f-4fd01895984d.png)

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已确认
