### ISSUE TITLE
前台 帮助页面 图片显示

### ISSUE THREAD

**Issue by ascar5** [ruoklive/lottery_bug#328]
https://web.ruok.co/#help
![default](https://user-images.githubusercontent.com/11421461/36058850-37e476d2-0e66-11e8-8f7a-ef2e57ad3f93.PNG)
显示不了图片

**Comment by chansent** [comment]
![image](https://user-images.githubusercontent.com/22720451/36061046-50e9a91c-0e8f-11e8-9553-6f6efabb53da.png)
已修正@ascar5

**Comment by ruoktest** [comment]
确认，反复问题
