### ISSUE TITLE
登录历史 底部最后一栏压盖 不能够滑动

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#34]
<img width="1277" alt="2018-01-18 10 33 50" src="https://user-images.githubusercontent.com/31721950/35079640-62166984-fc3b-11e7-9422-2b1f6ca17e8e.png">

**Comment by tonyisid** [comment]
这个页面已经废弃，会在“全部菜单”里删除

**Comment by ruoktest** [comment]
已确认
