### ISSUE TITLE
我的资料一片空白

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#35]
<img width="1264" alt="2018-01-18 10 37 26" src="https://user-images.githubusercontent.com/31721950/35079694-a2e1bf86-fc3b-11e7-9bac-656dd2cf9b1f.png">

**Comment by tonyisid** [comment]
我的个人资料的路由是个人中心，该页面已经没有用了。

**Comment by ruoktest** [comment]
已验证
