### ISSUE TITLE
全部->新会员->字段新增Undefined 描叙不对

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#36]
<img width="1218" alt="2018-01-18 10 59 46" src="https://user-images.githubusercontent.com/31721950/35080250-e570c2e0-fc3e-11e7-9411-b22d49823387.png">

**Comment by HangZyc** [comment]
上午跟设计沟通了，全部中屏蔽所有新增的功能导航。

**Comment by ruoktest** [comment]
确认
