### ISSUE TITLE
IP 搜索没有记录，输入一个IP也没响应

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#37]
<img width="1268" alt="2018-01-18 11 17 39" src="https://user-images.githubusercontent.com/31721950/35080614-49a8f898-fc41-11e7-8357-54a01ef4e4ac.png">

**Comment by WWcodeTW** [comment]
`{"status":1,"msg":"日期格式错误","_login_user_id":1,"_login_user_type":0,"_login_user_super":1,"_login_user_testing":0,"_login_master_super":1,"_login_master_type":0,"_login_master_id":1,"_route":"users_ip_record"}`
2018-01-18 12:12:12 要這種格式

**Comment by ruoktest** [comment]
已验证
