### ISSUE TITLE
【IOS】登录，没有提示信息

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#39]
1、输入手机号
2、输入错误的密码
3、点击登录
4、无任何反应，应该弹出提示信息，如：填写的用户名或密码错误

**Comment by huangjianguohjg** [comment]
![291516266058_ pic](https://user-images.githubusercontent.com/19162597/35089234-e5f2d670-fc68-11e7-90f5-6a220f539455.jpg)
解决

**Comment by ruoktest** [comment]
已验证
