### ISSUE TITLE
【pc chrome】手工存入金额过大时，toast文案提示不对

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#4]
![wx20180116-145505](https://user-images.githubusercontent.com/35476103/34975641-be22fe50-facd-11e7-8110-48292c39e456.png)

**Comment by tonyisid** [comment]
这个如果有限制，我可以在前端限制。
最大的cashin额度是多少呢？

**Comment by patrickkh7788** [comment]
后台加上了100万的限制，前台可以先不处理。

**Comment by ruoktest** [comment]
已验证
