### ISSUE TITLE
【Android】登录，没有提示信息

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#40]
1、输入手机号
2、输入错误的密码
3、点击登录
4、弹出提示，请检查你的网络（实际网络正确，其它app打开页都正常），应该提示：账号或密码错误，
5、在该页面的忘记密码页面会很快的显示一些数字（一闪而过）

**Comment by edem** [comment]
請問一閃而過的數字, 是在忘記密碼頁面, 輸入手機號時, 按"下一步"時出現的嗎? 如果是, 那是環形進度條.

**Comment by edem** [comment]
手機向後台查詢時, 若網路無法連上後台, 也會提示"请检查您的网络", 
連不上後台, 未必是手機本身網路有問題, 有可能問題出在後台的網路, 或是中間經過的網路節點, 這樣的話, 其他 App 照樣能上網.
目前輸入錯誤密碼, 的確是顯示 "账号或密码错误"

**Comment by edem** [comment]
請問這一條還有要補充的嗎? 是否還有異常?

**Comment by edem** [comment]
1. "請檢查你的網路", 是因為後台回覆時間逾時.
2. 一閃而過的數字, 其實是環型進度條.
還有要補充的嗎?
