### ISSUE TITLE
【Android】客户端进行用户注册时，键盘弹起后，注册页面不可上下滑动

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#43]
1、进入Android客户端页面进行新用户注册，需输入5栏
2、当输入到下面的栏位时（键盘挡住输入框），注册页面不可上下滑动，待优化
![aca1624f3ada157ed6392cc5a2cd8f9e](https://user-images.githubusercontent.com/35476103/35089617-680cebe2-fc72-11e7-84cd-9ff9b165469f.jpg)
![a9d24689df224041050cb57f1d7ea8d4](https://user-images.githubusercontent.com/35476103/35089619-6a0b5690-fc72-11e7-994a-43a1a6c688b2.jpg)

**Comment by edem** [comment]
新版本已經修改如下:
1. 鍵盤升起時, 會把輸入欄位往上頂, 不會再有鍵盤遮蔽輸入欄位的問題.
2. 手指觸動欄位以外的位置, 鍵盤即自動收起, 不需要滑動拖曳頁面.

**Comment by ruoktest** [comment]
已验证
