### ISSUE TITLE
【客户端】进入登录页面，用户框文案，请确认是否优化

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#45]
1、目前客户端（ios，Android）是展示文案：请输入手机号
2、当用户实际情况下有时输入的是用户名，待确认文案是否调整
![d197decde829b672a4e6d68079f038d0](https://user-images.githubusercontent.com/35476103/35089785-ebbe9198-fc72-11e7-99cc-f7999abb4ce7.jpg)

**Comment by huangjianguohjg** [comment]
![301516269414_ pic](https://user-images.githubusercontent.com/19162597/35091996-afe09a92-fc70-11e7-864d-15ac8a26846c.jpg)
ios have fixed
