### ISSUE TITLE
【香港六合彩】玩法【连尾】规则火爆彩票与cpcp彩票逻辑有出入，需确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#46]
1、已第2018003期开奖号码：47、49、31、29、3、43、19（尾数：1 3 7 9）
2、cpcp彩票中奖规则：不限顺序，7个开奖号的尾数中包含全部所选尾号，即为中奖
3、火爆彩票玩法规则：当期号码（所有正码与最后出的特码）坐落于投注时所勾选之尾数组合所属号码内，则视为中奖，其余情形视为不中奖
4、购彩投注：
      a、投注 二尾碰：1 3尾数的号码----->不中奖
      b、投注 三尾碰：1 3 7 尾数的号码--->不中奖
      c、投注  四尾碰：1 3 7 9尾数的号码-->不中奖
      d、投注 物尾碰：1 3 7 9 5尾数的号码---->不中奖    
5、通过以上投注确认： 
      开奖号码的所有尾数 包括所投注的尾数------->不中奖（cp彩票的逻辑，这里不符合）
      所投注的尾数 包括开奖号码的所有尾数-------->不中奖（火爆彩票的逻辑，这里也不符合）
6、请协助确认如何中奖呢？
![a8b54ba4a57eab2d77e17df0c0678bf9](https://user-images.githubusercontent.com/35476103/35092546-b7ee9752-fc7a-11e7-8451-ffffd9619ce3.jpg)
![329c8f3ab96e222fe479b0dff66f6ded](https://user-images.githubusercontent.com/35476103/35092548-ba1c4326-fc7a-11e7-9661-7703abba9df5.jpg)
![98043bcc2033caf127822bbf12fae408](https://user-images.githubusercontent.com/35476103/35092554-bcaced70-fc7a-11e7-894d-fd5c9736aa77.jpg)
![3cea7a6eb315fe309a506a552c7a2845](https://user-images.githubusercontent.com/35476103/35092561-bf126fea-fc7a-11e7-967b-ff87c287ec73.jpg)

**Comment by ascar5** [comment]
连尾开奖bug 已修复  中奖逻辑是所有购买尾数必须 # 所有 出现在开奖号码里 才算中

**Comment by ruoktest** [comment]
已验证
