### ISSUE TITLE
后台存取款报表页面问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#47]
<img width="1260" alt="a1" src="https://user-images.githubusercontent.com/35476103/35097775-1a98408e-fc84-11e7-9e56-068ab59e0476.png">

问题一：如果是人工存入以及人工取出的，应当要标明    人工存入  或者  人工取出   

问题二：右下角的总收支公式：   总存款金额-存款优惠-取款金额

**Comment by ruoktest** [comment]
<img width="952" alt="a2" src="https://user-images.githubusercontent.com/35476103/35097906-ca43bc02-fc84-11e7-901e-a512460d8388.png">


人工取出的备注也需要调节成非必填项目

**Comment by ruoktest** [comment]
<img width="942" alt="a3" src="https://user-images.githubusercontent.com/35476103/35098043-3df1b500-fc85-11e7-97d3-3e3c98b9746c.png">
<img width="977" alt="a4" src="https://user-images.githubusercontent.com/35476103/35098044-3e2c2096-fc85-11e7-80de-d246879f7665.png">
人工存款新问题：

存款优惠无法操作。

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/15
类似bug可以放在一个issue里，这个存入的地方麻烦 @205043957 再加上其他优惠的金额（参数见文档）。

**Comment by patrickkh7788** [comment]
存取款方式请使用： transfer_type 字段

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/16

**Comment by ruoktest** [comment]
确认
