### ISSUE TITLE
【pc Chrome】当用户金额满99999999.99以后，还继续投注的话，返还金额会显示错误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#5]
![wechatimg37](https://user-images.githubusercontent.com/35476103/34976299-e9171094-fad0-11e7-8f8b-cb7a5151657c.jpeg)
![wx20180116-151827](https://user-images.githubusercontent.com/35476103/34976301-eb7ad17c-fad0-11e7-85c9-65446f332157.png)

**Comment by ruokco** [comment]
add 标签

**Comment by patrickkh7788** [comment]
充值金额太多会导致这个问题，目前最大充值金额限制为100万。 
投注赢钱金额也在前台加了限制，用户账户不会出现没有业务意义的金额。
