### ISSUE TITLE
添加通知公告失败的时候，提示框没有文案

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#52]
![wx20180118-223718](https://user-images.githubusercontent.com/35476103/35130922-50d6a6c0-fcfe-11e7-8561-cbade0e3837a.png)

**Comment by tonyisid** [comment]
具体怎么发送错误？前端已经有代码显示错误了，需要后端确认是否返回了错误信息。

**Comment by ruoktest** [comment]
已确认
