### ISSUE TITLE
【pc opear】同一浏览器下，但多个子页面同时打开，只会锁屏一个页面

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#53]
![wx20180119-080256](https://user-images.githubusercontent.com/35476103/35130824-d3ec2d6a-fcfd-11e7-8518-b4531c67e6cd.png)

**Comment by tonyisid** [comment]
是登录还是锁屏？

**Comment by HangZyc** [comment]
目前锁屏改为整站锁屏。统一浏览器下，只要触发锁屏，新开窗口也会被锁住。其中一个页面解锁，切换到其他页面后，也会自动解锁。

**Comment by ruoktest** [comment]
已验证
