### ISSUE TITLE
【后台】安全版块下的登录历史，搜索条件[所在地]，没有搜索效果，需确认是否为issue

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#55]
![wqp 274oxkz 7 n j44b](https://user-images.githubusercontent.com/35476103/35131507-736cf768-fd01-11e7-80dd-aaf6a49506bb.png)

**Comment by tonyisid** [comment]
UI 上有这个搜索条件，但是后端目前不支持

**Comment by patrickkh7788** [comment]
@tonyisid 
这个过滤条件是： login_location  不是address。

**Comment by tonyisid** [comment]
已经改了过滤字段

**Comment by ruoktest** [comment]
已验证
