### ISSUE TITLE
【后台】版块安全里的IP搜素，输入框里条件文案换行了，需确认UI是否优化

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#56]
![9in hqtz 7nxrbd1me8ip0](https://user-images.githubusercontent.com/35476103/35131653-59c14854-fd02-11e7-90a3-6fc439c2419c.png)

**Comment by bihuademon** [comment]
是的，不能换行 这种下拉前端把宽度写宽些，是现在宽度2倍左右，然后固定写死

**Comment by ruoktest** [comment]
已验证
