### ISSUE TITLE
【后台】版块安全下的子账号 操作栏位的 “删除”不可选，需确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#59]
![q r7 ui3z o0 fgn4i 8](https://user-images.githubusercontent.com/35476103/35133653-541e1e7c-fd0c-11e7-88ef-62fbde4bc998.png)

**Comment by tonyisid** [comment]
后端目前是不可以删除用户的，建议加一个disable的选项，对外是删除，disable之后不在列表里显示，也不可以登录。

**Comment by patrickkh7788** [comment]
disbale 是通过 user_status 操作的。

**Comment by 205043957** [comment]
子账户的删除操作就是停用子账户,页面已有,删除不必要的按钮

**Comment by ruoktest** [comment]
已验证
