### ISSUE TITLE
【后台UI，后台API】后台进入时,怎么刷新都进不去，都停留在123456锁屏密码页面

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#6]
密码正确，刷新都停留在123456锁屏密码页面

**Comment by tonyisid** [comment]
是锁屏页面吗？能否给出重现的步骤

**Comment by ruokco** [comment]
步骤：1、输入网址，2、登陆成功，3、网页记住登陆密码，4、下次直接输入网址时，就停留在锁屏密码界面，无法退出，输入123456也没有反应
也就是，我正常进入后，网页记录密码，等下次再想进入，点击网址就是那样了

**Comment by tonyisid** [comment]
我重试了几次，没有出现这个问题。
另外输入锁屏密码可能会有网络延迟，可以看看验证锁屏密码的API是否正常返回数据

**Comment by patrickkh7788** [comment]
1. 测试结束后，后台会强制单点登录，也就是限制为一个浏览器登录。（踢出之前登录账号）
2. 在一个浏览器再次打开超时的话是应该请求验证锁屏api（将来可以考虑在输入密码时候需要同事输入图片验证码）
3. 没有测试到锁屏密码超时或者无法返回的情况，前端是否可以加个请求超时判断

**Comment by tonyisid** [comment]
fixed
