### ISSUE TITLE
【后台】股东--新建的股东数据信息都填写完整，在设定里查看部分贡显示这空白

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#60]
1、基本资料   会员账号：ADC123456  基本数据都已填写完
2、点击设置，其中登录密码、取款密码为空，（建议显示*****表示填写过）
3、生日项也显示为空

**Comment by tonyisid** [comment]
密码不能通过API回传，太不安全，所以暂时显示为空。
生日项 后端没有具体字段存储。

**Comment by ruoktest** [comment]
已确认

**Comment by ruoktest** [comment]
验证通过，关闭
