### ISSUE TITLE
【后台】版块安全下的子账号，创建子账号成功后，子账号登录后台成功后，显示不正确

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#61]
1、以test账号登录后台，进行创建子账号：wl654，密码：iloveyou3333333
2、使用创建的子账号进行登录后台，显示登录成功，并进行相关操作（改动其它子账号权限）
3、查看子账号页面，确认【在线】状态的信号灯为暗的
4、突出子账号，再以test账号登录，查询子账号 wl654的登录历史及操作历史，显示为空，没有记录到，需确认
![9kdl 9lesz wgwf0 e8si](https://user-images.githubusercontent.com/35476103/35134061-d8254b26-fd0e-11e7-9c5c-80ce574c784c.png)
![gd0d bka1 7z bgur5bup](https://user-images.githubusercontent.com/35476103/35134062-dbdce83c-fd0e-11e7-8ea9-0d5b12cc634b.png)

**Comment by tonyisid** [comment]
在线状态应该是1分钟更新一次。需要后端确认一下。
登录历史和操作历史目前后端的数据是有问题，需要修复。

**Comment by patrickkh7788** [comment]
@tommady 
在线状态调用任何接口就会更新，顶部有个tasks 每分钟调用一次更新。

>> 突出子账号，再以test账号登录，查询子账号 wl654的登录历史及操作历史，显示为空，没有记录到，需确认

这个打开后，api有提示错误的："不支持的过滤类型: filters[user_name]"
应该传入： https://admin.ruok.co/cn/api/log/login?page=1&page_each=30&user_id=1489&from=20180101&to=20180120&_ruoute_uri=%2Flog_login%3Fusername%3Dwl654
https://admin.ruok.co/cn/api/log/action?page=1&page_each=20&user_id=1489&from=20180101&to=20180120

**Comment by tonyisid** [comment]
我看到这个错误了，是否要把登录账号的查询去掉？
但是全网查询日志的时候应该是允许根据账号名进行查询的。

**Comment by tonyisid** [comment]
fixed
