### ISSUE TITLE
【后台】工单支持里面的我的工单，页面显示有两页，但点击无法跳转到下一页

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#62]
1、进入我的工单页面，确认有两页
2、点击 按钮：下一页------>不跳转
3、点击 按钮：页码2-------->不跳转
4、点击 输入框2 --------->不跳转
请确认
![ltb 24 c1 _oqz0 u11](https://user-images.githubusercontent.com/35476103/35134272-38d35ef8-fd10-11e7-9b8a-cf1478d41acc.png)

**Comment by tommady** [comment]
OK, 我檢查一下是否跟今天早上工單server 當機有關係.

**Comment by tommady** [comment]
已經確認是前端問題, 已修復.

**Comment by ruoktest** [comment]
已验证
