### ISSUE TITLE
【后台】工单支持内的我的工单，进行查看补充问题内容，点击提交失败，无反应

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#63]
![wd b z b19o nd oe4r83l6](https://user-images.githubusercontent.com/35476103/35136510-fa342e98-fd1e-11e7-8a88-9ffbd5d611af.png)

**Comment by tommady** [comment]
這個好像是工單那台機器全部當掉, 我會詢問老楊是否修復.

**Comment by tommady** [comment]
後端測試正常, 等待前端push code to fix this

**Comment by tonyisid** [comment]
我试了，应该是好的

**Comment by ruoktest** [comment]
当补充问题添加图片时，依旧提交失败，请确认
![cen98s 3uioj4hw r245 g](https://user-images.githubusercontent.com/35476103/35180343-4e13a2c6-fde9-11e7-8b85-e9922d9df2aa.png)

**Comment by tonyisid** [comment]
目前前端测试下来，是上传图片失败

**Comment by ruokco** [comment]
@WWcodeTW 文件上传重新部署了一台机器 你把文件上传地址改为http://188.166.227.244:8080/ 
这个你要改成配置 上线的时候地址是会变化的
