### ISSUE TITLE
【后台】版块工具下的子项 群聊 点击后无反应

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#64]
1、二级导航：群聊、红包、公告、活动中，群聊点击无反应
2、红包栏位下的 聊天室列表与红包统计，不可相互切换
![9 8i v3 aib q ofnq lv](https://user-images.githubusercontent.com/35476103/35137092-77b1673e-fd22-11e7-89b7-9f02740c1b2e.png)

**Comment by patrickkh7788** [comment]
chrome 不能重现，打是有数据的。

**Comment by ruoktest** [comment]
确认，没有复现
