### ISSUE TITLE
【后台】总代理列表，导出excel 后中文出现乱码

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#66]
【后台】总代理列表，导出excel 后中文出现乱码

**Comment by ruoktest** [comment]
导出后中文依旧会乱码（所有的列表导出都是），是需要额外设置格式吗

**Comment by tonyisid** [comment]
有刷新过页面吗？
我也确认一下修改是否上传部署

**Comment by 205043957** [comment]
![image](https://user-images.githubusercontent.com/18372025/35255485-e27d7574-0021-11e8-8cad-cff2dc00be50.png)

**Comment by 205043957** [comment]
我这边的中文是正常的，有可能没有上传部署

**Comment by 205043957** [comment]
目前我用线上的服务下载下来的 csv 没有出现中文乱码现象

**Comment by ruoktest** [comment]
确认（目前线下依旧乱码，后续线上确认）

**Comment by ruoktest** [comment]
确认csv文件，导出后用Excel打开需要将其编码改为ANSI的格式，后用Excel打开确认ok
需开发确认：后续上线后若后台人员使用Excel打开csv文件（且不会转码的情况），可否做一个兼容？

**Comment by 205043957** [comment]
我用的 execl 是微软的 2013版本的，打开中文是好的，你们的 excel 版本是哪个？？

**Comment by ruoktest** [comment]
确认
