### ISSUE TITLE
【后台】总代理，查询条件  时间 用20180215当天的，但也查出了2018019号的数据

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#69]
【后台】总代理，查询条件  时间 用20180215当天的，但也查出了2018019号的数据
![4](https://user-images.githubusercontent.com/35476103/35137681-a97766bc-fd25-11e7-98b5-3d52604570fa.png)

**Comment by tonyisid** [comment]
目前时间查询只会影响反水总额

**Comment by ruoktest** [comment]
已验证
