### ISSUE TITLE
首页->会员列表-投注信息里面的详情连接调到首页

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#7]
<img width="1272" alt="2018-01-16 6 51 53" src="https://user-images.githubusercontent.com/31721950/34987702-b4ccba3c-faee-11e7-8cfd-c5174d9ab2ee.png">

<img width="1254" alt="2018-01-16 6 52 00" src="https://user-images.githubusercontent.com/31721950/34987714-c2dcfb1e-faee-11e7-8574-1d3e656519f4.png">

点击详情调到首页

**Comment by tonyisid** [comment]
这个UI里面没有指定跳出什么页面，需要UI说明以下

**Comment by bihuademon** [comment]
跳到这个注单的弹窗详情页
![image](https://user-images.githubusercontent.com/35594060/35182070-c13e8d64-fe08-11e7-91bf-176fc7f18fd6.png)

**Comment by tonyisid** [comment]
@bihuademon 这个注单详情是对单注的，用户详情里面的那个表是针对彩种分类的集合。

**Comment by bihuademon** [comment]
那你觉得，跳到，注单搜索那里，按照，这个人，这个彩种，搜索出来的结果呈现怎么样？

**Comment by bihuademon** [comment]
如果可以，就这样做吧

**Comment by tonyisid** [comment]
做了跳转，只传了彩种，没有带时间，因为时间查询注单报表头部的时间查询条件冲突

**Comment by patrickkh7788** [comment]
如果不能传递时间的话，这样的详情意义就不大了。  可以不匹配tab上级的时间头直接传过去可以吗？
