### ISSUE TITLE
【后台】版块工具下的红包：发红包统计和领取人统计，当不输入任何筛选条件时，显示为空

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#70]
![6k3q dr0 q_ej wo ck91k](https://user-images.githubusercontent.com/35476103/35137914-c842781a-fd26-11e7-8498-4d85f27e6fab.png)

**Comment by patrickkh7788** [comment]
默认时间在UI上没有处理，显示为空的话是选择时间段内没有人发送红包。可以加上提示。

**Comment by tonyisid** [comment]
默认本月把

**Comment by ruoktest** [comment]
已验证
