### ISSUE TITLE
【后台】工具下的红包统计，当输入框 红包金额 输入实际数字时，显示的搜索结果不准确

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#71]

**Comment by patrickkh7788** [comment]
接口一个min_amount， max_amount。  目前传入的只是min_amount

**Comment by tonyisid** [comment]
是否将红包金额改成一个下来选项，最大红包金额和最小红包金额？

**Comment by patrickkh7788** [comment]
下拉选项目用户可以输入的话就可以满足业务需求。

**Comment by bihuademon** [comment]
![image](https://user-images.githubusercontent.com/35594060/35181859-0ffb44a0-fe05-11e7-8894-834b4e57b16c.png)
@tonyisid   按照这么做：比如如果第一个写了500，第二个框没写或是2个框都写500，就是选择大于等于500的，这个部件公告推送里mayon写过，样式已经跟进在zeplin里了，你看下。

**Comment by 205043957** [comment]
子账户的删除操作就是停用子账户,页面已有,删除不必要的按钮

**Comment by 205043957** [comment]
已经加入文字提示，输入的为最小金额

**Comment by ruoktest** [comment]
已确认
