### ISSUE TITLE
【后台】股东，银行卡，设置提现密码，但还显示是空白，并且下次编辑时，提交会提示，提现密码未设置

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#74]
1、股东--银行卡，设置提现密码，现次进入，还是显示空白，提交时，提现密码未设置，提示文案需要统一
![4](https://user-images.githubusercontent.com/35476103/35139164-dfc4157e-fd2c-11e7-96b7-36fdba6695c0.png)

**Comment by patrickkh7788** [comment]
已修复！

**Comment by ruoktest** [comment]
确认：输入提现密码后，会弹出 保存成功，但刷新或者重新进入该页面后，提现密码还是为空，而不是******，需确认是bug吗

**Comment by patrickkh7788** [comment]
提现密码没有必要显示为*****， 显示为空没有问题。

**Comment by ruoktest** [comment]
确认 不是bug
