### ISSUE TITLE
【后台】版块产品设置列表，提现更改成功后，数据依旧跳转为原数据，需确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#75]
1、后台版块 产品设置列表，更改相关彩票的赔率设置，点击提交显示出成功，但数据依然跳转为原数据
2、需确认此事bug，还是后台特意写死，针对这块测试过程不能做改动？
![r_ ay3rxfaw7h19_p kw bh](https://user-images.githubusercontent.com/35476103/35139347-a8452574-fd2d-11e7-8dab-53ff16a9783a.png)

**Comment by patrickkh7788** [comment]
保存已经修复

@tonyisid 
传统彩的保存需要传入odds数组以及dynamic_layouts数组，否则会提示错误。

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已确认
