### ISSUE TITLE
【后台】股东，查看会员页面下面的快捷操作无反映

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#76]
1、点击账号gudong1，查看他的详情页
2、点击会员数37，打开会员列表页
3、在会员列表页，点击右侧的快捷操作，无反映
![2](https://user-images.githubusercontent.com/35476103/35140109-f8fbd60e-fd30-11e7-8040-e4a0ec360dc1.png)

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已验证
