### ISSUE TITLE
【后台】功能收款银行卡管理中添加银行卡，选择银行下拉框无数据，也不可手动输入

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#78]
![3f689mpkd2v 5v1f qfg2b1](https://user-images.githubusercontent.com/35476103/35140507-74d1983a-fd32-11e7-8bb4-14c02de9ff6c.png)

**Comment by patrickkh7788** [comment]
api: banks 显示银行列表。

银行列表只在 card_types = 银行汇款的时候显示。
