### ISSUE TITLE
【后台】财务设置里的添加第三方支付后，操作栏选择删除，显示成功但数据没有变化

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#79]
1、进入后台财务设置里的添加第三方支付：支付宝哈哈哈
2、查看第三方支付列表，以显示
3、点击操作栏的删除，提示删除成功，但是页面依旧显示此账号（刷新重进都显示
![a2k 06kynp74 toqec29s](https://user-images.githubusercontent.com/35476103/35141572-4c398816-fd36-11e7-93bb-e7a02f4be084.png)
）

**Comment by patrickkh7788** [comment]
第三方支付是无法删除的。 可以通过thirdpart_status接口停止使用。
