### ISSUE TITLE
登录历史 没有log 

### ISSUE THREAD

**Issue by ruokco** [ruoklive/lottery_bug#8]
![image](https://user-images.githubusercontent.com/31721950/34988248-b2ee4dd2-faf0-11e7-8cc4-4cd5a9e90f36.png)

**Comment by tonyisid** [comment]
后端返回的数据是空的
需要后端检查一下

**Comment by patrickkh7788** [comment]
登录日志可以显示，操作日志@ WillianLiao 前台日志你也同事处理一下。（下单，提现等操作记录下来）

**Comment by patrickkh7788** [comment]
@WWcodeTW

**Comment by ruoktest** [comment]
已验证
