### ISSUE TITLE
【后台】财务设置里的添加第三方支付后，输入搜索条件：支付名称点击搜索按钮无反应

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#80]
![or s obzd h_9 p p69p40w](https://user-images.githubusercontent.com/35476103/35141688-c36a2a8a-fd36-11e7-95cc-ad8530be21e8.png)

**Comment by 205043957** [comment]
已经修复

**Comment by ruoktest** [comment]
刚退出后重新进入后台确认，输入支付名称搜索，依旧没有响应
