### ISSUE TITLE
后台新建股东以及新增直属会员

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#81]
<img width="1277" alt="a7" src="https://user-images.githubusercontent.com/35476103/35150886-be812af6-fd4e-11e7-9f97-280ad47de65f.png">

新增股东页面，
问题一：显示会员帐号文本有误
问题二：底下的区域不完整。

**Comment by ruoktest** [comment]
<img width="1279" alt="a8" src="https://user-images.githubusercontent.com/35476103/35150971-1096693c-fd4f-11e7-9d37-aaf0927b97ef.png">
操作流程：新增完毕股东，点击设定，  再点左侧的盘口进入赔率设置，标签丢失。

**Comment by ruoktest** [comment]
<img width="1272" alt="a9" src="https://user-images.githubusercontent.com/35476103/35151479-0cf92362-fd51-11e7-8aab-4ce44853cf88.png">

新增直属会员时，无法选择上级。   同时注意：这里的选择上级里面只有三个层级：   运营商/股东/总代理

**Comment by patrickkh7788** [comment]
创建直属会员的api： /cn/api/user/create?user_type_id=6  包含一个 parent_types 的数据。递交调用就可以出现 运营商 股东 总代等的选择。 请参考 https://admin.ruok.co/cn/member/addsonmember 实现

**Comment by tonyisid** [comment]
直属会员的创建，他的父级应该是当前登录的用户还是可以选择其他用户？
正常的话，父级选项是在parents里的。
@patrickkh7788 的意思是获得parent_types的数据后，还需要调用什么接口获取父级选项？

**Comment by ruoktest** [comment]
默认当前用户，   
若登陆方为运营商，则可自由选择股东，总代
若登陆方为股东，默认是股东这个级别，然后股东能自由选择属于他线下的总代线。

**Comment by tonyisid** [comment]
已经修复。

**Comment by ruoktest** [comment]
验证通过，关闭
