### ISSUE TITLE
后台-复制链接按钮无效。

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#82]
<img width="1273" alt="a9" src="https://user-images.githubusercontent.com/35476103/35151260-402df83a-fd50-11e7-8758-033446393675.png">

但实际无效，而且后台的所有该提示框的固定显示时间太长。应当优化。

**Comment by tonyisid** [comment]
我这里可以复制啊，你是windows吗？

**Comment by ruoktest** [comment]
我用的是苹果的  safari

**Comment by tonyisid** [comment]
已经修复。
