### ISSUE TITLE
后台--会员设定页面问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#83]
<img width="1128" alt="a10" src="https://user-images.githubusercontent.com/35476103/35151670-c8cdbb5c-fd51-11e7-9b45-a2ce2488bced.png">

以下问题主要出现于用户未绑定银行信息，若需重现请修改其它帐号。
问题一：经过测试，目前系统将所有的  微信，QQ，邮箱，地址等强制必填，应当调节为非必填。
问题二：所有项目均已填写后，又提示如图银行不存等提示。
问题三：后经多次尝试修改了密码，但前台登陆一直都是帐号或密码错误。

**Comment by ruoktest** [comment]
<img width="1273" alt="a11" src="https://user-images.githubusercontent.com/35476103/35151895-a07c3d1c-fd52-11e7-9adc-35126d04cbef.png">

所有的后台银行卡界面，除非用户未使用姓名，或者已经有绑定过一次银行卡操作，那么  开户人姓名应当锁定，修改需要验证后台操作密码（该操作密码为后台统一，非当前操作者的登陆密码）

**Comment by patrickkh7788** [comment]
“除非用户未使用姓名“（开户名字为空）， ”或者已经有绑定过一次银行卡操作”（开户名字不为空）。 

这个条件是否是 ？
 1： “用户未使用姓名“，允许修改。
 2:  “ 开户人姓名已经存在”， 输入后台操作码修改。

**Comment by patrickkh7788** [comment]
@tonyisid 
目前用户保存我看你调用的是 /cn/api/user/part/save，  这个接口可以是只出入一部分数据的时候保存的。（例如修改设定的时候不需要传入银行卡以及赔率数据），目前全部数据都传入了。

**Comment by patrickkh7788** [comment]
验证后台操作密码（权限密码）的API ：  check_super_password

**Comment by tonyisid** [comment]
目前是什么意思呢？是修改了什么就传什么保存吗？
微信，QQ，邮箱，地址 应该还是选填的把？

**Comment by patrickkh7788** [comment]
目前是什么意思呢？是修改了什么就传什么保存吗？ （我感觉应该是保存当前页面出现的项目）
微信，QQ，邮箱，地址 （已经修改为选填了）
