### ISSUE TITLE
【PC】首页 > 产品设置列表 > 传统重庆时时彩，修改“平台最大总利润”时，报错：没有odds

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#88]
![qq 20180120153557](https://user-images.githubusercontent.com/35476103/35181169-d4035800-fdf7-11e7-92c6-8fad21a6a952.png)

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/75

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/75

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
确认：设置更改  首页 > 产品设置列表 > 传统重庆时时彩，修改“平台最大总利润”时，依旧报缺少odds请确认是否异常，感谢

**Comment by tonyisid** [comment]
是异常。之前弄错了，看的是官方彩。
正在看。
