### ISSUE TITLE
【PC】配置-财务设置-第三方支付：全选失败

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#89]
![qq 20180120161717](https://user-images.githubusercontent.com/35476103/35181492-98776a82-fdfd-11e7-9763-e157c8058574.png)

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/90

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已验证
