### ISSUE TITLE
【PC】配置 - 财务设置 - 第三方支付：删除某一种第三方支付方式时，提示未选中

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#90]
![qq 20180120161746](https://user-images.githubusercontent.com/35476103/35181498-c24d4f48-fdfd-11e7-8ffa-130d4ef08ece.png)

**Comment by patrickkh7788** [comment]
@tonyisid
不能删除。 可以去掉停用启用以及多选按钮。

**Comment by tonyisid** [comment]
fixed

**Comment by ruoktest** [comment]
已验证
