### ISSUE TITLE
【后台】首页 > 用户组列表 > 编辑用户组：部分问题

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#91]
1、存款/取款的“笔数”不是每次都能修改；
2、当“总额”>“单笔最大金额”时，会保存成功；
3、没有展示出“会员数”“存款总额”；
4、此处功能和配置>网站配置>资金，功能重复了，而且金额冲突的时候，APP是以“资金为准的”

![qq 20180120165700](https://user-images.githubusercontent.com/35476103/35181763-f31eb828-fe02-11e7-8461-9ceff4011f6c.png)
![qq 20180120164750](https://user-images.githubusercontent.com/35476103/35181765-fc30ba88-fe02-11e7-9d89-1693e6316f30.png)

**Comment by patrickkh7788** [comment]
列表里的会员数和存款总额使用： user_count user_acount 字段显示。

保存不了是日志系统报错，@WWcodeTW 在logs保存函数里截取下长度，try cache excpetion

**Comment by patrickkh7788** [comment]
```sh
is_default boolean : 运营商可编辑 会员注册默认级别 0=默认 1=非默认
getnum integer : 运营商可编辑 取款笔数
gettotal integer : 运营商可编辑 取款总额
savetotal integer : 运营商可编辑 存款总额
savenum integer : 运营商可编辑 存款笔数
savemax integer : 运营商可编辑 存款最大金额
daymaxnum integer : 运营商可编辑 单日最大取款次数
remark text : 运营商可编辑 备注
sorts integer : 运营商可编辑 排序
```
这几个选项只有运营商可编辑（_login_master_super=1）。

**Comment by tonyisid** [comment]
user_count user_acount 已经修改
其他的还需要我这边修改什么？

**Comment by patrickkh7788** [comment]
把编辑以及列表里的 存款， 笔数，总额，最大金额，取款的取款笔数，取款总额去掉。

保留  单日最大取款次数 daymaxnum。添加max_withdrawal_amount_daily 单日最大提款金额， min_withdrawal_amount单笔最小提款金额。

**Comment by tonyisid** [comment]
已经修改了
