### ISSUE TITLE
后台---汇总报表点击查看会员下注明细详情有误

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#92]
<img width="1279" alt="a1" src="https://user-images.githubusercontent.com/35476103/35182072-6a6ee77a-fe00-11e7-8fb9-4dd11e33e590.png">
<img width="1276" alt="a2" src="https://user-images.githubusercontent.com/35476103/35182073-6aaf4bb2-fe00-11e7-8eb7-efe402a21664.png">

问题一：将详情页面的     流水一栏去掉，在有效投注后面增加输赢栏（统计的是相应彩种单独输赢情况）

问题二：我在报表汇总那里，看到的  会员  975511111   这个会员的注单数据跟我在详情页面查看到的数据应当保持一致！！！！

**Comment by patrickkh7788** [comment]
问题二：我在报表汇总那里，看到的 会员 975511111 这个会员的注单数据跟我在详情页面查看到的数据应当保持一致！！！！

汇总报表显示的是当天数据，和详情页不一样。

**Comment by bihuademon** [comment]
问题1：@tonyisid 按上述说的修改
问题2: 两边是不一样的数据统计，不用改的

**Comment by tonyisid** [comment]
已经修改

**Comment by ruoktest** [comment]
已验证

**Comment by ruoktest** [comment]
阿阳：该问题未按要求正常解决。
           用户详情页面，应该默认显示的是当天，然后才是增加可选   本周   本月  以及时间段选项。
否则运营商根本无法查询会员当天下的具体哪些注单，
          问题二：点击后面的详情，直接跳转到首页，应该是显示符合条件的订单清单。

**Comment by ruoktest** [comment]
2-8号复测，已有方案解决此问题，故关闭。
