### ISSUE TITLE
【PC】排列三彩票玩法前二码组选 中奖说明文案需优化，请确认

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#93]
排列三彩票玩法前二码组选与后二码组选应该应该都不应该包括对子，但中奖说明文案没有说明，请确认是否优化

![default](https://user-images.githubusercontent.com/35476103/35183581-9a1aa0ae-fe23-11e7-8c65-10a5dede6392.jpg)
![default](https://user-images.githubusercontent.com/35476103/35183582-9a641c98-fe23-11e7-82f9-088320642f6c.png)

**Comment by ascar5** [comment]
组选不用包含对子，已修改文案

**Comment by ruoktest** [comment]
已验证
