### ISSUE TITLE
【后台】香港六合彩，两面玩法和局情况下，开奖后开奖状态为：已取消，是否需要修改

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#94]
1、确认和局情况下资金可正常返回用户，但开奖状态却显示：已取消，请确认是否修改
![5gfjxs_pbx 4vd5k p c bl](https://user-images.githubusercontent.com/35476103/35183785-a4f03004-fe26-11e7-8a57-14ea5ea8cab9.png)

**Comment by ruoktest** [comment]
RE：2017140期开奖号码为    49   很多玩法都是为和  退还本金的，    和大  是指特码如  39即 3+9 这个和值。

**Comment by ruoktest** [comment]
开奖逻辑正常，但是和局，显示的开奖状态为“已取消，感觉和撤单一样，是否做调整呢

**Comment by ascar5** [comment]
之前撤单 和 和的描述都是已取消， 现在撤单的描述是撤单， 只有和是取消

**Comment by ruoktest** [comment]
确认
