### ISSUE TITLE
【后台】公司入款申请，填写了拒绝原因后，点击查看，拒绝原因还是显示空白（无填写）

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#96]
【后台】公司入款申请，填写了拒绝原因后，点击查看，拒绝原因还是显示空白（无填写）

**Comment by patrickkh7788** [comment]
拒绝原因是remark字段，api里已经提供了。
在拒绝后列表里的状态没有变更（拒绝后应该显示为拒绝状态，通过后不用在列表里）。

**Comment by patrickkh7788** [comment]
https://github.com/ruoklive/lottery_bug/issues/97
https://github.com/ruoklive/lottery_bug/issues/100

**Comment by tonyisid** [comment]
remark字段已经修正
@patrickkh7788 通过后，不用显示在列表里吗？

**Comment by patrickkh7788** [comment]
我说错了，需要显示。但是状态需要修改。

**Comment by ruoktest** [comment]
![image](https://user-images.githubusercontent.com/35476103/35260273-a0c234e8-0045-11e8-8f10-ece1180c150e.png)
已验证
