### ISSUE TITLE
【后台】公司入款申请，点击拒绝申请成功后，审核通过的按钮还可能点击

### ISSUE THREAD

**Issue by ruoktest** [ruoklive/lottery_bug#97]
【后台】公司入款申请，点击拒绝申请成功后，审核通过的按钮还可能点击
![1](https://user-images.githubusercontent.com/35476103/35191561-0e6a5a68-feb9-11e7-91f4-0500b83faecf.png)

**Comment by tonyisid** [comment]
有一点时间要去拉取新数据

**Comment by patrickkh7788** [comment]
公司入款的列表，缺少类似线上入款那样的根据状态过滤的功能。

**Comment by tonyisid** [comment]
what kind of filters need add, @luispuentesvega can talk to @patrickkh7788

**Comment by luispuentesvega** [comment]
Fixed, with the PR "Fix bug #97"

**Comment by ruoktest** [comment]
确认
